# SPDX-License-Identifier: LicenseRef-PointSav-ARR
# SPDX-FileCopyrightText: 2026 Woodfine Capital Projects Inc.
#
# This file is proprietary material of Woodfine Capital Projects Inc.
# See the LICENSE file in this repository for the full terms.
# Unauthorized use, reproduction, or distribution is prohibited.


[package]
name = "orchestration-command-server"
version = "0.0.1"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "orchestration-command-server"
path = "src/main.rs"

[dependencies]
orchestration-command-core = { workspace = true }
orchestration-command = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
