//! Curation-layer-presence check (`BRIEF-category-index-guide-redesign.md` Queue #26,
//! check 2 — spec: `.agent/audit/category-redesign-fable-pass.md` §R2-6 Check 2).
//!
//! `iceberg_ratio` measures *how much* of a category is surfaced. This measures whether what
//! is surfaced has real curatorial structure at all: a working "start here" pointer, and
//! shelf sections a human wrote an intro sentence for — as opposed to a flat enumeration of
//! every member with nothing said about any of it.
//!
//! Usage: `cargo run --example curation_layer_present -- <path-to-wiki-content-root>`
//!
//! # Sub-checks (Fable §R2-6 Check 2, a–d), applied to `_index` pages with M >= 8
//!
//! * **(a) `start_here_count`** — zero or more than one `START-HERE-HIGHLIGHT` block. The
//!   block's own inline comment says "Do not add more than one"; nothing enforced it.
//! * **(b) `start_here_resolves`** — the start-here card's link must resolve to a live
//!   member of this category.
//! * **(c) `shelf_without_prose`** — an H2 section whose content is *only* an AUTO block,
//!   with no hand-written sentence introducing it (the contextualised-link rule: every shelf
//!   gets at least one sentence).
//! * **(d) `pure_dump`** — an `_index` whose entire body after the lede is AUTO blocks.
//!
//! # Simplification, deliberate
//!
//! The spec says to "extend `markdown.rs` to expose H2 boundaries and non-AUTO prose spans".
//! H2 boundaries are already exposed (`Heading::offset`), and `AutoGeneratedBlock` gained an
//! `end` span in the same commit as `iceberg_ratio`, so a section's prose is computed here
//! as "the section span minus every AUTO block span" rather than as a new library type. If a
//! third consumer needs the same slicing it should move into `markdown.rs`; two does not
//! justify the API surface yet.
//!
//! A "sentence" is any run of >= `MIN_PROSE_CHARS` non-marker characters. Deliberately crude:
//! the defect this catches is a section with *nothing* written, not one written badly.
//!
//! Report-only.

use std::collections::BTreeMap;
use std::env;
use std::path::Path;

use tool_wiki_core::Document;

const START_MARKER: &str = "<!-- START-HERE-HIGHLIGHT";
const START_END_MARKER: &str = "<!-- END-START-HERE-HIGHLIGHT -->";
/// Membership at or below which a category is exempt (matches `iceberg_ratio`'s INFO floor:
/// a category too small to curate is not a curation defect).
const MIN_MEMBERSHIP: usize = 8;
/// Shortest run of prose that counts as an introducing sentence.
const MIN_PROSE_CHARS: usize = 25;

const DEAD_STATUSES: &[&str] = &["archived", "retired", "superseded"];

fn is_live(doc: &Document) -> bool {
    let archived = doc
        .path
        .components()
        .any(|c| c.as_os_str().to_str() == Some(".archive"));
    let dead = doc
        .frontmatter
        .status()
        .map(|s| DEAD_STATUSES.contains(&s))
        .unwrap_or(false);
    !archived && !dead
}

fn is_index(doc: &Document) -> bool {
    doc.path
        .file_stem()
        .and_then(|s| s.to_str())
        .map(|s| s == "_index" || s == "_index.es")
        .unwrap_or(false)
}

fn is_spanish(doc: &Document) -> bool {
    doc.path.to_string_lossy().ends_with(".es.md")
}

/// Byte spans of every region that is machine-generated or machine-read markup rather than
/// hand-written prose: AUTO-GENERATED blocks and the START-HERE block.
fn generated_spans(doc: &Document) -> Vec<(usize, usize)> {
    let mut spans: Vec<(usize, usize)> = doc
        .auto_generated_blocks
        .iter()
        .map(|b| (b.offset, b.end))
        .collect();
    let mut from = 0usize;
    while let Some(rel) = doc.body[from..].find(START_MARKER) {
        let start = from + rel;
        let end = match doc.body[start..].find(START_END_MARKER) {
            Some(r) => start + r + START_END_MARKER.len(),
            None => doc.body.len(),
        };
        spans.push((start, end));
        from = end;
    }
    spans.sort();
    spans
}

/// The hand-written text inside `span`, with every generated region removed.
fn prose_in(doc: &Document, span: (usize, usize), generated: &[(usize, usize)]) -> String {
    let (lo, hi) = span;
    let mut out = String::new();
    let mut cursor = lo;
    for &(gl, gh) in generated {
        if gh <= lo || gl >= hi {
            continue;
        }
        if gl > cursor {
            out.push_str(&doc.body[cursor..gl.min(hi)]);
        }
        cursor = cursor.max(gh);
    }
    if cursor < hi {
        out.push_str(&doc.body[cursor..hi]);
    }
    out
}

/// True when `text` contains a real introducing sentence, ignoring the H2 heading line
/// itself, HTML comments, and bare list bullets.
fn has_intro_prose(text: &str) -> bool {
    text.lines()
        .map(str::trim)
        .filter(|l| {
            !l.is_empty()
                && !l.starts_with('#')
                && !l.starts_with("<!--")
                && !l.starts_with("- ")
                && !l.starts_with('|')
        })
        .any(|l| l.chars().count() >= MIN_PROSE_CHARS)
}

/// Every `START-HERE-HIGHLIGHT` block's inner text.
fn start_here_blocks(doc: &Document) -> Vec<String> {
    let mut out = Vec::new();
    let mut from = 0usize;
    while let Some(rel) = doc.body[from..].find(START_MARKER) {
        let start = from + rel;
        let (inner_end, next) = match doc.body[start..].find(START_END_MARKER) {
            Some(r) => (start + r, start + r + START_END_MARKER.len()),
            None => (doc.body.len(), doc.body.len()),
        };
        out.push(doc.body[start..inner_end].to_string());
        from = next;
    }
    out
}

fn main() {
    let root = env::args().nth(1).expect("usage: curation_layer_present <path>");
    let root = Path::new(&root);
    let crawl = tool_wiki_core::crawl(root).expect("crawl failed");

    let mut members: BTreeMap<(String, bool), Vec<&Document>> = BTreeMap::new();
    let mut indexes: BTreeMap<(String, bool), &Document> = BTreeMap::new();
    for d in crawl.documents.iter().filter(|d| is_live(d)) {
        let Some(cat) = d.frontmatter.category() else { continue };
        if tool_wiki_core::is_reserved_category(cat) {
            continue;
        }
        let key = (cat.to_string(), is_spanish(d));
        if is_index(d) {
            indexes.insert(key, d);
        } else {
            members.entry(key).or_default().push(d);
        }
    }

    println!("crawled {} documents\n", crawl.documents.len());

    let mut findings = 0usize;
    let mut checked = 0usize;
    for (key, index) in &indexes {
        let member_count = members.get(key).map(Vec::len).unwrap_or(0);
        if member_count < MIN_MEMBERSHIP {
            continue;
        }
        checked += 1;
        let lang = if key.1 { "es" } else { "en" };
        let label = format!("{} [{lang}] ({} members)", key.0, member_count);
        let mut local: Vec<String> = Vec::new();

        // (a) exactly one START-HERE block
        let blocks = start_here_blocks(index);
        match blocks.len() {
            0 => local.push("(a) no START-HERE-HIGHLIGHT block — no start-here card renders".into()),
            1 => {}
            n => local.push(format!(
                "(a) {n} START-HERE-HIGHLIGHT blocks — the block's own comment says \"Do not add more than one\""
            )),
        }

        // (b) the start-here link resolves to a live member of this category
        if let Some(block) = blocks.first() {
            let member_slugs: Vec<&str> = members
                .get(key)
                .map(|m| m.iter().filter_map(|d| d.frontmatter.slug()).collect())
                .unwrap_or_default();
            let target = tool_wiki_core::markdown::wikilinks(block)
                .into_iter()
                .map(|w| w.target)
                .next();
            match target {
                None => local.push("(b) START-HERE block contains no wikilink".into()),
                Some(t) if !member_slugs.contains(&t.as_str()) => local.push(format!(
                    "(b) start-here link `{t}` is not a live member of `{}`",
                    key.0
                )),
                Some(_) => {}
            }
        }

        // (c)/(d) per-H2 shelf prose
        let generated = generated_spans(index);
        let h2s: Vec<&tool_wiki_core::markdown::Heading> =
            index.headings.iter().filter(|h| h.level == 2).collect();
        let mut shelves_with_auto = 0usize;
        let mut shelves_without_prose: Vec<&str> = Vec::new();
        for (i, h2) in h2s.iter().enumerate() {
            let end = h2s.get(i + 1).map(|n| n.offset).unwrap_or(index.body.len());
            let span = (h2.offset, end);
            let holds_auto = index
                .auto_generated_blocks
                .iter()
                .any(|b| b.offset >= span.0 && b.offset < span.1);
            if !holds_auto {
                continue;
            }
            shelves_with_auto += 1;
            if !has_intro_prose(&prose_in(index, span, &generated)) {
                shelves_without_prose.push(&h2.text);
            }
        }
        for shelf in &shelves_without_prose {
            local.push(format!(
                "(c) shelf \"{shelf}\": AUTO block with no hand-written intro sentence"
            ));
        }

        // (d) pure dump — every AUTO-bearing shelf is prose-free, and there is more than one
        if shelves_with_auto > 1 && shelves_without_prose.len() == shelves_with_auto {
            local.push(format!(
                "(d) pure dump — all {shelves_with_auto} shelves are AUTO blocks with no prose"
            ));
        }

        if !local.is_empty() {
            findings += local.len();
            println!("{}:", label);
            for l in &local {
                println!("  {l}");
            }
        }
    }

    println!(
        "\nchecked {checked} `_index` pages with >= {MIN_MEMBERSHIP} members; {findings} findings"
    );
}

#[cfg(test)]
mod curation_tests {
    use super::*;
    use std::path::PathBuf;

    fn doc(content: &str) -> Document {
        Document::parse(PathBuf::from("x/_index.md"), content).unwrap()
    }

    const FM: &str = "---\ntitle: \"X\"\nslug: x-index\ncategory: x\ncontent_type: topic\n---\n\n";

    #[test]
    fn counts_start_here_blocks() {
        let one = doc(&format!(
            "{FM}Lede.\n\n<!-- START-HERE-HIGHLIGHT: comment -->\n\n**Start here:** [[a]] — why.\n\n<!-- END-START-HERE-HIGHLIGHT -->\n"
        ));
        assert_eq!(start_here_blocks(&one).len(), 1);

        let two = doc(&format!(
            "{FM}Lede.\n\n<!-- START-HERE-HIGHLIGHT -->\n**Start here:** [[a]]\n<!-- END-START-HERE-HIGHLIGHT -->\n\n<!-- START-HERE-HIGHLIGHT -->\n**Start here:** [[b]]\n<!-- END-START-HERE-HIGHLIGHT -->\n"
        ));
        assert_eq!(start_here_blocks(&two).len(), 2);

        assert_eq!(start_here_blocks(&doc(&format!("{FM}Just a lede.\n"))).len(), 0);
    }

    #[test]
    fn a_shelf_with_an_intro_sentence_passes_and_one_without_fails() {
        let body = format!(
            "{FM}Lede paragraph long enough to count as real prose here.\n\n\
## Written shelf\n\nThe foundational structural articles that compose every deployment.\n\n\
<!-- AUTO-GENERATED MEMBERSHIP: DO NOT EDIT BELOW — regenerate from index_group: one -->\n- [[a]] — d.\n<!-- END AUTO-GENERATED -->\n\n\
## Bare shelf\n\n\
<!-- AUTO-GENERATED MEMBERSHIP: DO NOT EDIT BELOW — regenerate from index_group: two -->\n- [[b]] — d.\n<!-- END AUTO-GENERATED -->\n"
        );
        let d = doc(&body);
        let generated = generated_spans(&d);
        let h2s: Vec<_> = d.headings.iter().filter(|h| h.level == 2).collect();
        assert_eq!(h2s.len(), 2);

        let written = prose_in(&d, (h2s[0].offset, h2s[1].offset), &generated);
        assert!(has_intro_prose(&written));

        let bare = prose_in(&d, (h2s[1].offset, d.body.len()), &generated);
        assert!(!has_intro_prose(&bare), "a shelf that is only an AUTO block has no intro");
    }

    /// The AUTO block's own bullet text must not be mistaken for an intro sentence -- that
    /// would make sub-check (c) silently always pass.
    #[test]
    fn auto_block_bullets_never_count_as_shelf_prose() {
        let body = format!(
            "{FM}Lede.\n\n## Bare\n\n\
<!-- AUTO-GENERATED MEMBERSHIP: DO NOT EDIT BELOW — regenerate from index_group: one -->\n\
- [[a]] — a description long enough to pass the prose length floor on its own.\n\
<!-- END AUTO-GENERATED -->\n"
        );
        let d = doc(&body);
        let generated = generated_spans(&d);
        let h2 = d.headings.iter().find(|h| h.level == 2).unwrap();
        assert!(!has_intro_prose(&prose_in(&d, (h2.offset, d.body.len()), &generated)));
    }

    #[test]
    fn the_start_here_block_is_not_counted_as_shelf_prose() {
        let body = format!(
            "{FM}Lede.\n\n## Shelf\n\n\
<!-- START-HERE-HIGHLIGHT -->\n**Start here:** [[a]] — a fairly long start-here sentence.\n<!-- END-START-HERE-HIGHLIGHT -->\n\n\
<!-- AUTO-GENERATED MEMBERSHIP: DO NOT EDIT BELOW — regenerate from index_group: one -->\n- [[a]] — d.\n<!-- END AUTO-GENERATED -->\n"
        );
        let d = doc(&body);
        let generated = generated_spans(&d);
        let h2 = d.headings.iter().find(|h| h.level == 2).unwrap();
        assert!(
            !has_intro_prose(&prose_in(&d, (h2.offset, d.body.len()), &generated)),
            "the machine-read START-HERE card is markup, not the shelf's own intro"
        );
    }
}
