#!/usr/bin/env python3
"""
build-wildfire-join.py — GWIS FWI classified raster → wildfire_hazard + fwi_class per cluster

Samples gwis-fwi-classified.tif (already generated by build-aec-flood.sh Night 5)
using struct to avoid numpy 2.x / GDAL incompatibility.

FWI class → wildfire_hazard string (Canadian Forest Service scale):
  0 = no/very_low (NoData — skip)
  1 = low    (FWI 5.2–11.2)
  2 = moderate (FWI 11.2–21.3)
  3 = high   (FWI 21.3–38.0)
  4 = very_high (FWI 38.0+)
  5 = extreme

Source: GWIS (Global Wildfire Information System), CC BY 4.0
"""
import json, struct, fcntl
from pathlib import Path

try:
    from osgeo import gdal
except ImportError:
    raise SystemExit("ERROR: osgeo/gdal not available")

META_PATH   = Path("/srv/foundry/deployments/gateway-orchestration-gis-1/www/data/clusters-meta.json")
RASTER_PATH = Path("/srv/foundry/deployments/gateway-orchestration-gis-1/app-orchestration-gis/work/aec/gwis-fwi-classified.tif")

FWI_LABELS  = {1: 'low', 2: 'moderate', 3: 'high', 4: 'very_high', 5: 'extreme'}

if not RASTER_PATH.exists():
    raise SystemExit(f"ERROR: {RASTER_PATH} not found")

ds  = gdal.Open(str(RASTER_PATH))
gt  = ds.GetGeoTransform()
xsz = ds.RasterXSize
ysz = ds.RasterYSize

def sample(lon, lat):
    px = int((lon - gt[0]) / gt[1])
    py = int((lat - gt[3]) / gt[5])
    if not (0 <= px < xsz and 0 <= py < ysz):
        return 0
    buf = ds.ReadRaster(xoff=px, yoff=py, xsize=1, ysize=1)
    return struct.unpack('B', buf)[0] if buf else 0

print("Building GWIS wildfire_hazard join...")
clusters = json.loads(META_PATH.read_text())
total    = len(clusters)
already  = sum(1 for c in clusters if c.get('wildfire_hazard') is not None)
print(f"  {total} clusters; {already} already have wildfire_hazard")

n_new = 0
for c in clusters:
    if c.get('wildfire_hazard') is not None:
        continue
    v = sample(c.get('lon', 0), c.get('lat', 0))
    lbl = FWI_LABELS.get(v)
    if lbl:
        c['wildfire_hazard'] = lbl
        c['fwi_class'] = v
        n_new += 1

lock_path = META_PATH.with_suffix('.lock')
with open(lock_path, 'w') as lf:
    fcntl.flock(lf, fcntl.LOCK_EX)
    clusters_fresh = json.loads(META_PATH.read_text())
    for i, c in enumerate(clusters):
        if c.get('wildfire_hazard') is not None and clusters_fresh[i].get('wildfire_hazard') is None:
            clusters_fresh[i]['wildfire_hazard'] = c['wildfire_hazard']
            clusters_fresh[i]['fwi_class'] = c.get('fwi_class')
    META_PATH.write_text(json.dumps(clusters_fresh, separators=(',', ':')))

t_total = sum(1 for c in clusters_fresh if c.get('wildfire_hazard') is not None)
print(f"Done.")
print(f"  wildfire_hazard: {t_total}/{total} ({n_new} new)")
label_counts = {}
for c in clusters_fresh:
    lbl = c.get('wildfire_hazard')
    if lbl:
        label_counts[lbl] = label_counts.get(lbl, 0) + 1
for k, v in sorted(label_counts.items()):
    print(f"    {k}: {v}")
