#!/usr/bin/env python3
"""
build-flood-join.py — AQUEDUCT classified raster → flood_hazard per cluster

Samples aqueduct-flood-classified.tif (already generated by build-aec-flood.sh Night 1)
using struct (no numpy) to avoid the numpy 2.x / GDAL incompatibility.

Raster value → flood_hazard string:
  0 = no flood (skip)
  1 = very_low  (0–0.1 m 1-in-100yr inundation depth)
  2 = low       (0.1–0.5 m)
  3 = medium    (0.5–1.5 m)
  4 = high      (1.5–5 m)
  5 = very_high (> 5 m)

Source: WRI AQUEDUCT 3.0, CC BY 4.0
"""
import json, struct, fcntl
from pathlib import Path

try:
    from osgeo import gdal
except ImportError:
    raise SystemExit("ERROR: osgeo/gdal not available")
# Do NOT call gdal.DontUseExceptions() — triggers lazy gdal_array import which
# crashes under numpy 2.x (AttributeError: _ARRAY_API not found)

META_PATH    = Path("/srv/foundry/deployments/gateway-orchestration-gis-1/www/data/clusters-meta.json")
RASTER_PATH  = Path("/srv/foundry/deployments/gateway-orchestration-gis-1/app-orchestration-gis/work/aec/aqueduct-flood-classified.tif")

LABELS = {1: 'very_low', 2: 'low', 3: 'medium', 4: 'high', 5: 'very_high'}

if not RASTER_PATH.exists():
    raise SystemExit(f"ERROR: {RASTER_PATH} not found")

ds  = gdal.Open(str(RASTER_PATH))
gt  = ds.GetGeoTransform()
xsz = ds.RasterXSize
ysz = ds.RasterYSize

def sample(lon, lat):
    px = int((lon - gt[0]) / gt[1])
    py = int((lat - gt[3]) / gt[5])
    if not (0 <= px < xsz and 0 <= py < ysz):
        return 0
    buf = ds.ReadRaster(xoff=px, yoff=py, xsize=1, ysize=1)
    return struct.unpack('B', buf)[0]

print("Building AQUEDUCT flood_hazard join...")
clusters = json.loads(META_PATH.read_text())
total    = len(clusters)
already  = sum(1 for c in clusters if c.get('flood_hazard') is not None)
print(f"  {total} clusters; {already} already have flood_hazard")

n_new = 0
for c in clusters:
    if c.get('flood_hazard') is not None:
        continue
    v = sample(c.get('lon', 0), c.get('lat', 0))
    lbl = LABELS.get(v)
    if lbl:
        c['flood_hazard'] = lbl
        n_new += 1

lock_path = META_PATH.with_suffix('.lock')
with open(lock_path, 'w') as lf:
    fcntl.flock(lf, fcntl.LOCK_EX)
    clusters_fresh = json.loads(META_PATH.read_text())
    for i, c in enumerate(clusters):
        if c.get('flood_hazard') is not None and clusters_fresh[i].get('flood_hazard') is None:
            clusters_fresh[i]['flood_hazard'] = c['flood_hazard']
    META_PATH.write_text(json.dumps(clusters_fresh, separators=(',', ':')))

t_total = sum(1 for c in clusters_fresh if c.get('flood_hazard') is not None)
print(f"Done.")
print(f"  flood_hazard: {t_total}/{total} ({n_new} new)")
label_counts = {}
for c in clusters_fresh:
    lbl = c.get('flood_hazard')
    if lbl:
        label_counts[lbl] = label_counts.get(lbl, 0) + 1
for k, v in sorted(label_counts.items()):
    print(f"    {k}: {v}")
