// SPDX-License-Identifier: FSL-1.1-ALv2
// SPDX-FileCopyrightText: 2026 Woodfine Capital Projects Inc.

//! Dynamic product-catalog renderer for the `/software` storefront page.
//!
//! This module renders the marketplace catalog **from the same [`crate::Catalog`]
//! data that `v1_products` serves** — there is no second source of truth for real
//! products. Because the cards are generated by iterating the loaded catalog, the
//! page can never drift from `products.yaml`.
//!
//! **Phase 1b, holistic redesign.** Two structural decisions replace the earlier
//! (2026-07-07-ratified) two-shelf Commercial/Open-Source model:
//!
//! 1. **Architecture tiers (Infrastructure/Platform/Delivery) are now the page's
//!    only grouping axis**, in a deliberately Delivery-first order (see
//!    `TIER_ORDER`'s doc comment). License tier is not lost — it moves into each
//!    real card's derived "Distribution" fact row and stays fully explorable via
//!    `/licensing` — it's demoted from primary axis to per-card attribute. The
//!    two-shelf model currently rendered only one populated shelf anyway (zero
//!    `Apache`-tier products exist in `products.yaml`), so this costs no live
//!    structure.
//! 2. **Real products and roadmap items now share one page**, via the [`TierCard`]
//!    enum below. An earlier design rendered the roadmap as a structurally separate
//!    `/roadmap` page after an adversarial review found real risks in mixing them
//!    (drift, honesty, complexity). The operator later reviewed that shipped result
//!    and directed a merge. The two safety properties that review named survive,
//!    now enforced by a **type + module boundary** instead of a URL boundary:
//!    - **No drift**: `TierCard::Real` can only be built from a borrow into the
//!      loaded `Catalog`; `TierCard::Roadmap` can only be built from
//!      `roadmap::ROADMAP_ITEMS`, a `pub(crate)` const that never touches
//!      `products.yaml`. There is no third, hand-authored source — a card not
//!      built from one of these two is a compile error, not a discipline problem.
//!    - **No fake purchase signal**: `roadmap::roadmap_item_card` has no access to
//!      this module's `install_command`/`download_command`/checkout-link builder/
//!      `json_ld_script` — all private here. A roadmap card is *structurally
//!      incapable* of emitting a price, install/download block, or checkout link.
//!      `roadmap.rs`'s own tests guard this per-card; this module's
//!      `every_roadmap_card_on_the_merged_page_is_purchase_free` guards it again on
//!      the actual merged page.
//!
//! See `.agent/briefs/BRIEF-storefront-architecture-education.md` for the full
//! research trail (three design iterations, real competitor research, an
//! adversarial review) behind this shape.
//!
//! Fields NOT available in the catalog (noted rather than fabricated):
//!   - **sha256** — no SHA field exists on `Installer`. Per-artifact SHA256 lives on
//!     the release server's per-version `MANIFEST` endpoint, not in `products.yaml`.
//!
//! Pricing units: `price_usdc` is USDC base units (6 decimals), verified against
//! `tool-wallet/src/main.rs` (`$1.00 USDC = 1_000_000 units`). Displayed dollars are
//! `price_usdc as f64 / 1_000_000.0`.

use crate::ui::roadmap::{self, RoadmapItem};
use crate::ui::Lang;
use crate::{ArchTier, ArtifactKind, LicenseTier};
use maud::{html, Markup, PreEscaped};

/// One slot in a tier section's grid. The two variants are the page's only two data
/// sources, and there is deliberately no third — see this module's doc comment.
enum TierCard<'a> {
    Real(&'a crate::Installer),
    Roadmap(&'static RoadmapItem),
}

/// Page order: Delivery first, Platform second, Infrastructure last — a deliberate,
/// explicit inversion of `project-totebox/README.md`'s own bottom-up engineering
/// table. A storefront meets a visitor top-down, at the surface closest to what
/// they'll actually touch, not at the foundation underneath it. It also avoids
/// opening the page on the one tier with zero real, downloadable products today
/// (Infrastructure) — locked in via `tier_sections_render_in_delivery_platform_
/// infrastructure_order` below so a future "fix" doesn't silently revert it.
const TIER_ORDER: [ArchTier; 3] = [
    ArchTier::Delivery,
    ArchTier::Platform,
    ArchTier::Infrastructure,
];

/// Real products in this tier, then roadmap items in this tier — never
/// interleaved, never alphabetical. A visitor should read "here's what you can
/// have today" before "here's where this layer is going."
fn tier_cards<'a>(catalog: &'a crate::Catalog, tier: ArchTier) -> Vec<TierCard<'a>> {
    let mut cards: Vec<TierCard<'a>> = catalog
        .installers
        .iter()
        .filter(|i| i.tier == tier)
        .map(TierCard::Real)
        .collect();
    cards.extend(
        roadmap::ROADMAP_ITEMS
            .iter()
            .filter(|r| r.tier == tier)
            .map(TierCard::Roadmap),
    );
    cards
}

/// Build the curl-pipe-sh install command for a bare-binary product.
fn install_command(source_base_url: &str, id: &str) -> String {
    let base = source_base_url.trim_end_matches('/');
    format!("curl -fsSL {base}/{id}/install.sh | bash")
}

/// A dark terminal-style install-command block with a copy-to-clipboard button.
fn install_block(command: &str, lang: Lang) -> Markup {
    let l = lang.catalog_labels();
    html! {
        div."sw-cat-install" {
            div."sw-cat-cmd" {
                code."sw-cat-cmd__text" { (command) }
                button."sw-cat-cmd__copy" type="button"
                    data-sw-clip=(command) data-sw-label=(l.copy)
                    aria-label=(l.copy_aria) { (l.copy) }
            }
            p."sw-cat-hint" { (l.install_hint) }
        }
    }
}

/// Build the direct-download curl command for an `ArtifactKind::ApplianceImage`
/// product — there is nothing to "install" (curl-pipe-sh into bash makes no sense
/// for a boot image), so this just fetches the file to disk.
fn download_command(source_base_url: &str, id: &str, edition: &str, platform_slug: &str) -> String {
    let base = source_base_url.trim_end_matches('/');
    format!("curl -fsSL {base}/{id}/{edition}/{platform_slug} -o {platform_slug}")
}

/// The appliance-image counterpart to `install_block`.
fn download_block(command: &str, lang: Lang) -> Markup {
    let l = lang.catalog_labels();
    html! {
        div."sw-cat-install" {
            div."sw-cat-cmd" {
                code."sw-cat-cmd__text" { (command) }
                button."sw-cat-cmd__copy" type="button"
                    data-sw-clip=(command) data-sw-label=(l.copy)
                    aria-label=(l.copy_aria) { (l.copy) }
            }
            p."sw-cat-hint" { (l.download_hint) }
        }
    }
}

/// How this product's artifact is distributed — one clause of the derived
/// "Distribution" fact row (`card_fact_rows`), never authored in `products.yaml`.
fn artifact_label(kind: ArtifactKind) -> &'static str {
    match kind {
        ArtifactKind::CliBinary => "Native binary",
        ArtifactKind::ApplianceImage => "Appliance image",
    }
}

/// A real product's fact-row block: up to 3 authored facts from `products.yaml`,
/// plus a 4th, always-derived "Distribution" row (artifact kind/size/edition/
/// license) computed here, never authored — it can't drift from the rest of this
/// struct's own fields. Reuses `roadmap::fact_rows` verbatim — the same visual
/// contract real and roadmap cards share.
fn card_fact_rows(i: &crate::Installer) -> Markup {
    let distribution = format!(
        "{} \u{b7} {} MB \u{b7} {}",
        artifact_label(i.artifact),
        i.size_mb,
        i.license_tier.label()
    );
    let mut pairs: Vec<(&str, &str)> = i
        .facts
        .iter()
        .map(|f| (f.label.as_str(), f.value.as_str()))
        .collect();
    pairs.push(("DISTRIBUTION", distribution.as_str()));
    roadmap::fact_rows(&pairs)
}

/// The status row shared by every real card: an "Available now"/BETA-free/open-
/// source chip plus the version chip. Reuses `.sw-cat-status`/`.sw-cat-chip` — the
/// same visual language `roadmap::status_block` uses for "Not yet available", so a
/// visitor reads both card kinds as the same *kind* of thing, distinguished only by
/// which chip they carry.
fn real_status_row(i: &crate::Installer, lang: Lang) -> Markup {
    let l = lang.catalog_labels();
    let chip = if i.license_tier == LicenseTier::Apache {
        l.free_open_source
    } else if i.price_usdc == 0 {
        l.beta_free
    } else {
        l.available_now
    };
    html! {
        div."sw-cat-status" {
            span."sw-cat-chip" { (chip) }
            span."sw-cat-badge sw-cat-badge--ver" { "v" (i.edition) }
            span."sw-cat-badge" { (i.family.label()) }
        }
    }
}

/// Every real card's name links to its product-detail page — a real gap fixed in
/// Phase 1b (cards previously linked nowhere at all).
fn card_name_link(i: &crate::Installer, lang: Lang) -> Markup {
    html! {
        h3."sw-cat-card__name" {
            a href=(lang.localize(&format!("/software/{}", i.id))) { (i.name) }
        }
    }
}

fn becomes_line(i: &crate::Installer) -> Option<Markup> {
    i.becomes.as_ref().map(|b| {
        html! {
            p."sw-cat-card__becomes" { (b) }
        }
    })
}

/// A free/BETA product card — `price_usdc == 0`. Real curl-pipe-sh install
/// command, no payment step.
fn free_product_card(i: &crate::Installer, source_base_url: &str, lang: Lang) -> Markup {
    let command = install_command(source_base_url, &i.id);
    html! {
        article."sw-cat-card" {
            span."sw-cat-card__id" { (i.id) }
            (card_name_link(i, lang))
            @if let Some(becomes) = becomes_line(i) { (becomes) }
            p."sw-cat-card__desc" { (i.description) }
            (real_status_row(i, lang))
            (card_fact_rows(i))
            (install_block(&command, lang))
        }
    }
}

/// An `ArtifactKind::ApplianceImage` product card — a copy of `free_product_card`
/// with the curl-pipe-sh install block swapped for a direct-download block.
fn appliance_product_card(i: &crate::Installer, source_base_url: &str, lang: Lang) -> Markup {
    let command = download_command(source_base_url, &i.id, &i.edition, i.platform_slug());
    html! {
        article."sw-cat-card" {
            span."sw-cat-card__id" { (i.id) }
            (card_name_link(i, lang))
            @if let Some(becomes) = becomes_line(i) { (becomes) }
            p."sw-cat-card__desc" { (i.description) }
            (real_status_row(i, lang))
            (card_fact_rows(i))
            (download_block(&command, lang))
        }
    }
}

/// A paid product card — `price_usdc > 0` (BETA lifted for this product). Shows the
/// price and a Polygon-USDC pay CTA in place of the install/download terminal.
fn paid_product_card(i: &crate::Installer, lang: Lang) -> Markup {
    let dollars = i.price_usdc as f64 / 1_000_000.0;
    let checkout_href = format!("/checkout/{}", i.id);
    let l = lang.catalog_labels();
    let pay_aria = l.pay_aria_fmt.replace("{}", &i.name);
    html! {
        article."sw-cat-card" {
            span."sw-cat-card__id" { (i.id) }
            (card_name_link(i, lang))
            @if let Some(becomes) = becomes_line(i) { (becomes) }
            p."sw-cat-card__desc" { (i.description) }
            (real_status_row(i, lang))
            (card_fact_rows(i))
            div."sw-cat-price" {
                span."sw-cat-price__amt" { "$" (format!("{dollars:.2}")) }
                span."sw-cat-price__unit" { (l.price_unit) }
                div."sw-cat-pay" {
                    a."sw-cat-pay__cta" href=(checkout_href)
                        rel="nofollow" aria-label=(pay_aria) {
                        span."sw-cat-pay__mark" aria-hidden="true" { "\u{25C8}" }
                        (l.pay_cta)
                    }
                    p."sw-cat-pay__meta" { (l.pay_meta) }
                }
            }
        }
    }
}

/// Simple geometric glyphs distinguishing the 3 tiers — same lightweight-Unicode
/// approach this crate already uses elsewhere (`pay_cta`'s "\u{25C8}" mark,
/// roadmap's "\u{2192}" arrow), not hand-rolled SVG.
fn tier_glyph(tier: ArchTier) -> &'static str {
    match tier {
        ArchTier::Delivery => "\u{25b4}", // outward — what people touch
        ArchTier::Platform => "\u{2261}", // stacked layers — what runs and stores
        ArchTier::Infrastructure => "\u{25ac}", // a base — what it all stands on
    }
}

fn tier_blurb(tier: ArchTier, lang: Lang) -> &'static str {
    match (tier, lang) {
        (ArchTier::Delivery, Lang::En) =>
            "What people actually sit in front of \u{2014} the surfaces staff and operators use every day.",
        (ArchTier::Platform, Lang::En) =>
            "What runs and stores the work \u{2014} the archives, brokers, and command servers a deployment is assembled from.",
        (ArchTier::Infrastructure, Lang::En) =>
            "What the whole thing stands on \u{2014} the host layer that keeps a deployment on hardware you control.",
        (ArchTier::Delivery, Lang::Es) =>
            "Lo que su personal realmente utiliza \u{2014} las superficies que operadores y personal usan cada d\u{ed}a.",
        (ArchTier::Platform, Lang::Es) =>
            "Lo que ejecuta y almacena el trabajo \u{2014} los archivos, corredores y servidores de comando de un despliegue.",
        (ArchTier::Infrastructure, Lang::Es) =>
            "Sobre lo que se apoya todo \u{2014} la capa de host que mantiene un despliegue en hardware que usted controla.",
    }
}

/// Scoped stylesheet for the catalog surface. All selectors are `sw-cat-` prefixed.
/// Concatenates `roadmap::ROADMAP_CARD_CSS` — this module renders no page shell of
/// its own (Phase 1b), so its card-scoped rules land in this page's one `<style>`.
fn catalog_style() -> Markup {
    let css = format!(
        r#".sw-cat-wrap{{max-width:1280px;margin:0 auto;padding:40px 24px 64px;box-sizing:border-box;}}
.sw-cat-eyebrow{{margin:0 0 6px;font-size:12px;font-weight:600;letter-spacing:.1em;text-transform:uppercase;color:#234ed8;}}
.sw-cat-intro{{margin:0 0 10px;font-family:Georgia,"Times New Roman",serif;font-size:34px;line-height:1.15;color:#111827;}}
.sw-cat-lede{{margin:0 0 16px;color:#344054;font-size:18px;line-height:1.5;max-width:64ch;}}
.sw-cat-trust{{margin:0 0 32px;font-size:12px;letter-spacing:.04em;color:#667085;display:flex;gap:10px;flex-wrap:wrap;}}
.sw-cat-stats{{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;margin:0 0 32px;padding:20px 0;border-top:1px solid #e4e7ec;border-bottom:1px solid #e4e7ec;}}
.sw-cat-stat__num{{display:block;font-family:Georgia,"Times New Roman",serif;font-size:26px;color:#111827;}}
.sw-cat-stat__label{{display:block;margin-top:2px;font-size:11px;letter-spacing:.04em;text-transform:uppercase;color:#98a2b3;}}
.sw-cat-stat__label--standalone{{margin-top:0;padding-top:8px;font-size:13px;color:#475467;}}
.sw-cat-archband{{margin:0 0 40px;padding:20px 24px;background:#234ed8;border-radius:8px;}}
.sw-cat-archband__h{{margin:0 0 4px;font-family:Georgia,"Times New Roman",serif;font-size:18px;color:#fff;}}
.sw-cat-archband__deck{{margin:0 0 18px;font-size:13px;line-height:1.55;color:#eef3ff;max-width:70ch;}}
.sw-cat-archband__tiles{{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:12px;}}
.sw-cat-archtile{{display:block;padding:14px 16px;background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.18);border-radius:6px;color:#eef3ff;text-decoration:none;}}
.sw-cat-archtile:hover{{background:rgba(255,255,255,.14);}}
.sw-cat-archtile__glyph{{font-size:16px;color:#fff;}}
.sw-cat-archtile__name{{display:block;margin:4px 0 4px;font-family:Georgia,"Times New Roman",serif;font-size:15px;color:#fff;}}
.sw-cat-archtile__blurb{{margin:0 0 8px;font-size:12px;line-height:1.45;color:#eef3ff;}}
.sw-cat-archtile__count{{font-size:11px;color:rgba(255,255,255,.78);}}
.sw-cat-section{{margin:0 0 48px;}}
.sw-cat-section:last-child{{margin-bottom:0;}}
.sw-cat-section__h{{display:flex;align-items:baseline;gap:10px;font-size:13px;letter-spacing:.1em;text-transform:uppercase;color:#234ed8;margin:0 0 4px;}}
.sw-cat-section__glyph{{font-size:13px;}}
.sw-cat-section__count{{color:#98a2b3;font-size:11px;letter-spacing:normal;text-transform:none;font-weight:400;}}
.sw-cat-section__blurb{{margin:0 0 8px;font-size:13px;line-height:1.5;color:#475467;max-width:70ch;}}
.sw-cat-section__underline{{margin:0 0 18px;height:2px;background:#234ed8;border:0;}}
.sw-cat-subhead{{grid-column:1/-1;margin:8px 0 0;font-size:11px;letter-spacing:.04em;text-transform:uppercase;color:#98a2b3;}}
.sw-cat-grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:20px;}}
.sw-cat-card{{min-width:0;border:1px solid #e4e7ec;border-radius:10px;padding:20px;display:flex;flex-direction:column;background:#fff;box-shadow:0 1px 2px rgba(16,24,40,.04);transition:border-color .12s ease,box-shadow .12s ease;}}
.sw-cat-card:hover{{border-color:#b4c5d5;box-shadow:0 2px 8px rgba(22,70,121,.08);}}
.sw-cat-card__id{{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px;color:#667085;letter-spacing:.02em;}}
.sw-cat-card__name{{font-family:Georgia,"Times New Roman",serif;font-size:19px;line-height:1.2;color:#111827;margin:3px 0 6px;}}
.sw-cat-card__name a{{color:inherit;text-decoration:none;}}
.sw-cat-card__name a:hover{{color:#234ed8;}}
.sw-cat-card__becomes{{font-size:15px;font-weight:500;line-height:1.4;color:#111827;margin:0 0 8px;}}
.sw-cat-card__desc{{font-size:13.5px;line-height:1.5;color:#475467;margin:0 0 14px;}}
.sw-cat-badges{{display:flex;flex-wrap:wrap;gap:6px;margin:0 0 14px;}}
.sw-cat-badge{{font-size:11px;font-weight:600;letter-spacing:.02em;padding:3px 8px;border-radius:999px;background:#f2f4f7;color:#344054;white-space:nowrap;}}
.sw-cat-badge--ver{{background:#eef3ff;color:#234ed8;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;}}
.sw-cat-install{{margin-top:auto;}}
.sw-cat-cmd{{display:flex;align-items:stretch;background:#0e1117;border-radius:6px;overflow:hidden;}}
.sw-cat-cmd__text{{flex:1;min-width:0;color:#e6edf3;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;line-height:1.4;padding:9px 11px;overflow-x:auto;white-space:nowrap;}}
.sw-cat-cmd__copy{{border:0;background:#234ed8;color:#fff;font-size:11px;font-weight:600;padding:0 14px;cursor:pointer;letter-spacing:.04em;flex:0 0 auto;}}
.sw-cat-cmd__copy:hover{{background:#173ab1;}}
.sw-cat-hint{{font-size:11px;color:#98a2b3;margin:7px 0 0;}}
.sw-cat-price{{margin-top:auto;padding:12px 14px;border:1px solid #e4e7ec;border-radius:6px;background:#f8f9fa;}}
.sw-cat-price__amt{{font-size:20px;font-weight:700;color:#111827;font-family:Georgia,"Times New Roman",serif;}}
.sw-cat-price__unit{{font-size:12.5px;color:#667085;margin-left:6px;}}
.sw-cat-pay{{margin-top:12px;}}
.sw-cat-pay__cta{{display:inline-flex;align-items:center;justify-content:center;gap:8px;box-sizing:border-box;background:#234ed8;color:#fff;font-size:13px;font-weight:600;letter-spacing:.02em;text-decoration:none;padding:10px 16px;border-radius:6px;border:1px solid #234ed8;transition:background .12s ease;}}
.sw-cat-pay__cta:hover{{background:#173ab1;border-color:#173ab1;}}
.sw-cat-pay__cta:focus-visible{{outline:2px solid #234ed8;outline-offset:2px;}}
.sw-cat-pay__mark{{font-size:14px;line-height:1;}}
.sw-cat-pay__meta{{margin:8px 0 0;font-size:11.5px;line-height:1.45;color:#667085;}}
.sw-cat-footerband{{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:16px;margin:0 0 20px;padding:24px;background:#f8f9fa;border-radius:8px;}}
.sw-cat-footerband a{{color:#234ed8;font-weight:600;text-decoration:none;font-size:13.5px;}}
.sw-cat-footerband a:hover{{color:#173ab1;}}
.sw-cat-honesty{{margin:0;font-size:11.5px;color:#98a2b3;}}
@media (max-width:768px){{.sw-cat-grid{{grid-template-columns:1fr;}}.sw-cat-wrap{{padding:28px 16px 48px;}}.sw-cat-pay__cta{{display:flex;width:100%;padding:13px 16px;font-size:14px;}}.sw-cat-intro{{font-size:28px;}}}}
{}"#,
        roadmap::ROADMAP_CARD_CSS
    );
    html! { style { (PreEscaped(css)) } }
}

/// `SoftwareApplication` JSON-LD for `/software` — page-level, generic (never
/// per-product), which is exactly why a roadmap card can never carry one: this is
/// the only place this module emits it, and `roadmap.rs` has no access to it.
fn json_ld_script() -> Markup {
    let json = r#"{"@context":"https://schema.org","@type":"SoftwareApplication","name":"PointSav Software Marketplace","applicationCategory":"BusinessApplication","provider":{"@type":"Organization","@id":"https://pointsav.com/#organization"}}"#;
    html! {
        script type="application/ld+json" { (PreEscaped(json)) }
    }
}

/// Vanilla-JS copy-to-clipboard for every `[data-sw-clip]` control.
fn clipboard_script(lang: Lang) -> Markup {
    let copied = lang.catalog_labels().copied;
    let js = format!(
        r#"(function(){{
document.querySelectorAll('[data-sw-clip]').forEach(function(btn){{
  btn.addEventListener('click',function(){{
    var text=btn.getAttribute('data-sw-clip');
    if(!navigator.clipboard){{return;}}
    navigator.clipboard.writeText(text).then(function(){{
      var label=btn.getAttribute('data-sw-label')||btn.textContent;
      btn.textContent='{copied}';
      setTimeout(function(){{btn.textContent=label;}},1500);
    }}).catch(function(){{}});
  }});
}});
}})();"#
    );
    html! { script { (PreEscaped(js)) } }
}

fn tier_section(
    tier: ArchTier,
    catalog: &crate::Catalog,
    source_base_url: &str,
    lang: Lang,
) -> Markup {
    let cards = tier_cards(catalog, tier);
    let real_count = cards
        .iter()
        .filter(|c| matches!(c, TierCard::Real(_)))
        .count();
    let planned_count = cards.len() - real_count;
    let (count_text, also_h) = match lang {
        Lang::En => (
            match (real_count, planned_count) {
                (r, 0) => format!("{r} available"),
                (0, p) => format!("{p} planned"),
                (r, p) => format!("{r} available \u{b7} {p} planned"),
            },
            "Also in this tier \u{2014} not yet available",
        ),
        Lang::Es => (
            match (real_count, planned_count) {
                (r, 0) => format!("{r} disponibles"),
                (0, p) => format!("{p} planificados"),
                (r, p) => format!("{r} disponibles \u{b7} {p} planificados"),
            },
            "Tambi\u{e9}n en esta capa \u{2014} a\u{fa}n no disponible",
        ),
    };
    html! {
        @if !cards.is_empty() {
            section."sw-cat-section" id=(tier.slug()) {
                h2."sw-cat-section__h" {
                    span."sw-cat-section__glyph" aria-hidden="true" { (tier_glyph(tier)) }
                    (tier.label())
                    span."sw-cat-section__count" { (count_text) }
                }
                p."sw-cat-section__blurb" { (tier_blurb(tier, lang)) }
                hr."sw-cat-section__underline";
                div."sw-cat-grid" {
                    @for card in &cards {
                        @match card {
                            TierCard::Real(i) if i.artifact == ArtifactKind::ApplianceImage => {
                                (appliance_product_card(i, source_base_url, lang))
                            }
                            TierCard::Real(i) if i.price_usdc == 0 => {
                                (free_product_card(i, source_base_url, lang))
                            }
                            TierCard::Real(i) => {
                                (paid_product_card(i, lang))
                            }
                            TierCard::Roadmap(_) => {}
                        }
                    }
                    @if real_count > 0 && planned_count > 0 {
                        p."sw-cat-subhead" { (also_h) }
                    }
                    @for card in &cards {
                        @if let TierCard::Roadmap(r) = card {
                            (roadmap::roadmap_item_card(r, lang))
                        }
                    }
                }
            }
        }
    }
}

/// Render the full product catalog as body content for the `/software` page. See
/// this module's doc comment for the Phase 1b architecture (arch-tier grouping,
/// merged real+roadmap cards).
pub fn catalog_markup(catalog: &crate::Catalog, source_base_url: &str, lang: Lang) -> Markup {
    let l = lang.catalog_labels();
    let real_count = catalog.installers.len();
    let roadmap_count = roadmap::ROADMAP_ITEMS.len();

    let (
        trust_items,
        stat_available,
        stat_roadmap,
        stat_purchase,
        archband_h,
        archband_deck,
        footer_licensing,
        footer_roadmap_note,
        footer_contact,
        honesty,
    ) = match lang {
        Lang::En => (
            [
                "No subscription",
                "No cloud dependency",
                "No kill switch",
                "Your keys, your license",
            ],
            "Available to download today",
            "In design or active development",
            "One-time purchase, no subscription",
            "One stack, three layers",
            "The components of an orchestration, not an app store. What's ready has \
             a download command below it; what's still being built has a status \
             label instead \u{2014} and isn't for sale yet.",
            "Licensing \u{2014} every tier, in plain terms",
            "Roadmap \u{2014} marked in each tier above",
            "Contact \u{2014} talk to a human",
            "This catalog always matches what's actually available to download \
             \u{2014} nothing here is stale or hand-curated.",
        ),
        Lang::Es => (
            [
                "Sin suscripci\u{f3}n",
                "Sin dependencia de la nube",
                "Sin interruptor de apagado remoto",
                "Sus claves, su licencia",
            ],
            "Disponibles para descargar hoy",
            "En dise\u{f1}o o desarrollo activo",
            "Compra \u{fa}nica, sin suscripci\u{f3}n",
            "Una plataforma, tres capas",
            "Los componentes de una orquestaci\u{f3}n, no una tienda de aplicaciones. \
             Lo que ya est\u{e1} listo tiene un comando de descarga debajo; lo que \
             a\u{fa}n se est\u{e1} construyendo tiene una etiqueta de estado en su \
             lugar \u{2014} y todav\u{ed}a no est\u{e1} a la venta.",
            "Licencias \u{2014} cada nivel, en t\u{e9}rminos sencillos",
            "Hoja de ruta \u{2014} marcado en cada capa arriba",
            "Contacto \u{2014} hable con una persona",
            "Este cat\u{e1}logo siempre coincide con lo que realmente est\u{e1} \
             disponible para descargar \u{2014} nada aqu\u{ed} est\u{e1} \
             desactualizado ni curado a mano.",
        ),
    };

    html! {
        (catalog_style())
        (json_ld_script())
        div."sw-cat-wrap" {
            p."sw-cat-eyebrow" { (l.eyebrow) }
            h1."sw-cat-intro" { (l.title) }
            p."sw-cat-lede" { (l.lede) }
            div."sw-cat-trust" {
                @for (n, item) in trust_items.iter().enumerate() {
                    @if n > 0 { span aria-hidden="true" { "\u{b7}" } }
                    span { (item) }
                }
            }
            div."sw-cat-stats" {
                div."sw-cat-stat" {
                    span."sw-cat-stat__num" { (real_count) }
                    span."sw-cat-stat__label" { (stat_available) }
                }
                div."sw-cat-stat" {
                    span."sw-cat-stat__num" { (roadmap_count) }
                    span."sw-cat-stat__label" { (stat_roadmap) }
                }
                div."sw-cat-stat" {
                    span."sw-cat-stat__label sw-cat-stat__label--standalone" { (stat_purchase) }
                }
            }
            div."sw-cat-archband" {
                h2."sw-cat-archband__h" { (archband_h) }
                p."sw-cat-archband__deck" { (archband_deck) }
                div."sw-cat-archband__tiles" {
                    @for tier in TIER_ORDER {
                        a."sw-cat-archtile" href=(format!("#{}", tier.slug())) {
                            span."sw-cat-archtile__glyph" aria-hidden="true" { (tier_glyph(tier)) }
                            span."sw-cat-archtile__name" { (tier.label()) }
                            p."sw-cat-archtile__blurb" { (tier_blurb(tier, lang)) }
                        }
                    }
                }
            }
            @for tier in TIER_ORDER {
                (tier_section(tier, catalog, source_base_url, lang))
            }
            div."sw-cat-footerband" {
                a href=(lang.localize("/licensing")) { (footer_licensing) }
                span { (footer_roadmap_note) }
                a href=(lang.localize("/page/contact")) { (footer_contact) }
            }
            p."sw-cat-honesty" { (honesty) }
        }
        (clipboard_script(lang))
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────
//
// Pure rendering functions — no server, no filesystem, no network.
#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Catalog, Installer};

    const BASE: &str = "https://example.invalid/releases";

    fn fixture() -> Catalog {
        Catalog {
            installers: vec![
                Installer {
                    id: "test-mediakit".into(),
                    name: "MediaKit OS".into(),
                    description: "Sovereign media workstation image.".into(),
                    edition: "1.2.0".into(),
                    platform: "linux-x86_64".into(),
                    size_mb: 812,
                    path: "test-mediakit/1.2.0/installer.run".into(),
                    license_tier: LicenseTier::Fsl,
                    price_usdc: 0, // active BETA gate
                    fsl_conversion_date: None,
                    guide_url: None,
                    artifact: ArtifactKind::CliBinary,
                    platform_slug: None,
                    boot_notes: None,
                    tier: ArchTier::Delivery,
                    facts: vec![],
                    bundled_registry_products: vec![],
                    family: crate::ProductFamily::Independent,
                    becomes: None,
                },
                Installer {
                    id: "test-console".into(),
                    name: "Console OS".into(),
                    description: "Operator Terminal Surface.".into(),
                    edition: "1.0.0".into(),
                    platform: "linux-x86_64".into(),
                    size_mb: 150,
                    path: "test-console/1.0.0/installer.run".into(),
                    license_tier: LicenseTier::Agpl,
                    price_usdc: 19_000_000, // BETA lifted, test fixture only ($19)
                    fsl_conversion_date: None,
                    guide_url: None,
                    artifact: ArtifactKind::CliBinary,
                    platform_slug: None,
                    boot_notes: None,
                    tier: ArchTier::Platform,
                    facts: vec![],
                    bundled_registry_products: vec![],
                    family: crate::ProductFamily::Independent,
                    becomes: None,
                },
            ],
        }
    }

    #[test]
    fn install_command_shape_and_trailing_slash_handling() {
        assert_eq!(
            install_command(BASE, "test-mediakit"),
            "curl -fsSL https://example.invalid/releases/test-mediakit/install.sh | bash"
        );
        assert_eq!(
            install_command("https://example.invalid/releases/", "x"),
            "curl -fsSL https://example.invalid/releases/x/install.sh | bash"
        );
    }

    #[test]
    fn known_products_appear_in_rendered_markup() {
        let html = catalog_markup(&fixture(), BASE, Lang::En).into_string();
        assert!(html.contains("test-mediakit"));
        assert!(html.contains("MediaKit OS"));
        assert!(html.contains("test-console"));
        assert!(html.contains("Console OS"));
        // Phase 1b: grouped by architecture tier, not license tier — the fixture's
        // Delivery product and Platform product land in their own tier sections.
        assert!(html.contains(r#"id="delivery""#));
        assert!(html.contains(r#"id="platform""#));
        assert!(html.contains("<h2 class=\"sw-cat-section__h\">"));
        // License tier now shows up in the derived Distribution fact row, not a
        // section heading.
        assert!(html.contains("DISTRIBUTION"));
        assert!(html.contains("FSL-1.1-ALv2"));
        assert!(html.contains("AGPL-3.0-or-later"));
        // Badge row shows the fields that ARE in the catalog.
        assert!(html.contains("v1.2.0"));
        assert!(html.contains("812 MB"));
    }

    #[test]
    fn product_card_name_links_to_its_detail_page() {
        // Phase 1b: a real gap fixed — card names previously linked nowhere.
        let html = catalog_markup(&fixture(), BASE, Lang::En).into_string();
        assert!(html.contains(r#"<a href="/software/test-mediakit">MediaKit OS</a>"#));
        let html_es = catalog_markup(&fixture(), BASE, Lang::Es).into_string();
        assert!(html_es.contains(r#"<a href="/es/software/test-mediakit">MediaKit OS</a>"#));
    }

    #[test]
    fn software_page_carries_valid_software_application_json_ld() {
        let html = catalog_markup(&fixture(), BASE, Lang::En).into_string();
        let start = html
            .find(r#"<script type="application/ld+json">"#)
            .expect("JSON-LD script tag missing");
        let after_open = &html[start..];
        let json_start = after_open.find('>').unwrap() + 1;
        let json_end = after_open.find("</script>").unwrap();
        let json_text = &after_open[json_start..json_end];
        let parsed: serde_json::Value =
            serde_json::from_str(json_text).expect("JSON-LD must be valid JSON");
        assert_eq!(parsed["@type"], "SoftwareApplication");
        assert_eq!(parsed["@context"], "https://schema.org");
    }

    #[test]
    fn paid_product_renders_pricing_cta_and_no_install_command() {
        let html = catalog_markup(&fixture(), BASE, Lang::En).into_string();
        assert!(html.contains("$19.00"));
        assert!(html.contains("Pay with Polygon USDC"));
        assert!(html.contains("href=\"/checkout/test-console\""));
        assert!(
            !html.contains("releases/test-console/install.sh"),
            "paid product must NOT render an install command"
        );
    }

    #[test]
    fn free_products_render_curl_install_commands() {
        let html = catalog_markup(&fixture(), BASE, Lang::En).into_string();
        assert!(html.contains(
            "curl -fsSL https://example.invalid/releases/test-mediakit/install.sh | bash"
        ));
        assert!(html.contains("BETA · free"));
        assert!(html.contains("data-sw-clip"));
    }

    /// Phase 1b: a real semantic inversion, not just a rename. With zero real
    /// products, all 3 tier sections still render — each carries only its roadmap
    /// items and the explicit "no products yet" note. This is a *better* test than
    /// the one it replaces (which asserted sections vanished entirely): it's the
    /// actual shape the merge introduced, and it doubles as a purchase-signal guard.
    #[test]
    fn empty_catalog_renders_roadmap_only_sections_with_no_purchase_signals() {
        let empty = Catalog { installers: vec![] };
        let html = catalog_markup(&empty, BASE, Lang::En).into_string();
        assert!(html.contains("sw-cat-intro"));
        // No `id="delivery"` assertion: os-console (the only Delivery-tier roadmap
        // item) graduated to a real catalog product 2026-08-06 and was removed from
        // ROADMAP_ITEMS — with an empty catalog and no Delivery-tier roadmap item
        // left, that section genuinely doesn't render, which is correct behavior,
        // not a regression.
        assert!(html.contains(r#"id="platform""#));
        assert!(html.contains(r#"id="infrastructure""#));
        // Regression guard: an earlier "No products available in this tier yet."
        // note was removed as dead/misleading — `tier_section` only ever renders a
        // section when it has at least one card, real or roadmap, so that note could
        // never appear in a state where it was actually true (it always ran
        // immediately above a roadmap card contradicting it).
        assert!(!html.contains("No products available in this tier yet."));
        // Every roadmap item still renders...
        assert!(html.contains("os-infrastructure"));
        assert!(html.contains("os-workplace"));
        // ...but nothing on the page is purchasable. Check the rendered element
        // class attribute, not the bare class name (which always appears once,
        // harmlessly, inside the page's own embedded `<style>` CSS rule).
        assert!(!html.contains(r#"class="sw-cat-install""#));
        assert!(!html.contains(r#"class="sw-cat-price""#));
        assert!(!html.contains("/checkout/"));
    }

    #[test]
    fn products_are_grouped_by_architecture_tier_not_license_tier_or_prefix_family() {
        // Regression guard: the catalog only ever models os-* installers, and cards
        // are grouped by `tier` (Delivery/Platform/Infrastructure), never by
        // `license_tier` sections or an id-prefix family grid (Phase 1b supersedes
        // the earlier two-shelf-by-license-tier model).
        let html = catalog_markup(&fixture(), BASE, Lang::En).into_string();
        assert!(!html.contains("tool-wallet"));
        assert!(!html.contains("Wallet &amp; Tools"));
        assert!(!html.contains("Knowledge &amp; Source"));
        assert!(!html.contains(r#"id="proprietary""#));
        assert!(!html.contains(r#"id="fsl""#));
        assert!(!html.contains(r#"id="agpl""#));
        assert!(!html.contains(r#"id="open-source""#));
    }

    fn fixture_with_appliance() -> Catalog {
        let mut catalog = fixture();
        catalog.installers.push(Installer {
            id: "test-totebox".into(),
            name: "PointSav Totebox Archive".into(),
            description: "Boot-verified seL4/Microkit appliance image.".into(),
            edition: "0.1.0".into(),
            platform: "aarch64 (seL4 appliance image)".into(),
            size_mb: 115,
            path: "test-totebox/0.1.0/loader.img".into(),
            license_tier: LicenseTier::Fsl,
            price_usdc: 0,
            fsl_conversion_date: None,
            guide_url: None,
            artifact: ArtifactKind::ApplianceImage,
            platform_slug: Some("loader.img".into()),
            boot_notes: Some("Boot under QEMU/seL4 — see the product page.".into()),
            tier: ArchTier::Platform,
            facts: vec![],
            bundled_registry_products: vec![],
            family: crate::ProductFamily::Independent,
            becomes: None,
        });
        catalog
    }

    #[test]
    fn appliance_product_card_never_emits_an_install_sh_url() {
        let html = catalog_markup(&fixture_with_appliance(), BASE, Lang::En).into_string();
        assert!(html.contains("test-totebox"));
        assert!(!html.contains("test-totebox/install.sh"));
        assert!(html.contains(
            "curl -fsSL https://example.invalid/releases/test-totebox/0.1.0/loader.img -o loader.img"
        ));
        assert!(html.contains("Bootable appliance image"));
    }

    #[test]
    fn existing_cli_binary_products_are_unaffected_by_the_appliance_card_variant() {
        let html = catalog_markup(&fixture_with_appliance(), BASE, Lang::En).into_string();
        assert!(html.contains(
            "curl -fsSL https://example.invalid/releases/test-mediakit/install.sh | bash"
        ));
        assert!(html.contains("test-console"));
        assert!(html.contains("Pay with Polygon USDC"));
    }

    fn fixture_with_open_source() -> Catalog {
        let mut catalog = fixture();
        catalog.installers.push(Installer {
            id: "test-wallet".into(),
            name: "PointSav Wallet".into(),
            description: "Polygon USDC watcher, relicensed Apache-2.0.".into(),
            edition: "1.0.0".into(),
            platform: "linux-x86_64".into(),
            size_mb: 12,
            path: "test-wallet/1.0.0/installer.run".into(),
            license_tier: LicenseTier::Apache,
            price_usdc: 0,
            fsl_conversion_date: None,
            guide_url: None,
            artifact: ArtifactKind::CliBinary,
            platform_slug: None,
            boot_notes: None,
            tier: ArchTier::Platform,
            facts: vec![],
            bundled_registry_products: vec![],
            family: crate::ProductFamily::Independent,
            becomes: None,
        });
        catalog
    }

    #[test]
    fn open_source_free_badge_reads_open_source_not_beta() {
        // A permanently-free Apache-2.0 grant is not a "BETA" gate awaiting a future
        // price — the badge copy must not imply one, regardless of which tier
        // section the product renders in (Phase 1b: no longer a separate shelf).
        let html = catalog_markup(&fixture_with_open_source(), BASE, Lang::En).into_string();
        assert!(html.contains("Free \u{00b7} open source"));
        assert!(html.contains("BETA \u{00b7} free"));
    }

    #[test]
    fn hero_and_archband_carry_the_relocated_brand_copy() {
        // Binary Library brand voice — the established "buy it once… own it
        // forever" lede stays (load-bearing, tested elsewhere too); the two longer
        // clauses that used to sit in the lede paragraph relocate into the
        // architecture band per Phase 1b (the lede itself is now a single sentence
        // since its old closing clause — "nothing here is stale or hand-curated" —
        // would be factually false once part of the page is deliberately
        // hand-curated roadmap content; that honesty claim relocates to the footer).
        let html = catalog_markup(&fixture(), BASE, Lang::En).into_string();
        assert!(html.contains("The Binary Library"));
        assert!(html.contains("Buy it once. Run it anywhere. Own it forever."));
        assert!(html.contains("components of an orchestration, not"));
        assert!(html.contains("an app store"));
        assert!(html.contains("nothing here is stale or hand-curated"));
    }

    #[test]
    fn spanish_catalog_page_translates_chrome_but_not_product_data() {
        let html = catalog_markup(&fixture(), BASE, Lang::Es).into_string();
        assert!(html.contains("La Biblioteca Binaria"));
        assert!(html.contains("<h1 class=\"sw-cat-intro\">Productos</h1>"));
        assert!(html.contains("Una plataforma, tres capas"));
        assert!(html.contains("BETA \u{b7} gratis"));
        assert!(html.contains("Copiar"));
        // Product name/description text (from products.yaml) is untouched.
        assert!(html.contains("MediaKit OS"));
        assert!(html.contains("Sovereign media workstation image."));
        // Legal tier identifiers and architecture-tier labels stay untranslated on
        // both languages (same "product/taxonomy data" convention).
        assert!(html.contains("FSL-1.1-ALv2"));
        assert!(html.contains("Delivery"));
        assert!(html.contains("Platform"));
    }

    /// The direct guard for Phase 1b's core safety property, verified on the
    /// actual merged page rather than in `roadmap.rs`'s isolation tests alone — a
    /// page-level substring check can't be used here (the page legitimately
    /// contains `sw-cat-price`/`SoftwareApplication`/`/checkout/` for real
    /// products), so this slices by each roadmap card's own element boundary.
    #[test]
    fn every_roadmap_card_on_the_merged_page_is_purchase_free() {
        let html = catalog_markup(&fixture(), BASE, Lang::En).into_string();
        let slices: Vec<&str> = html
            .match_indices(r#"<article class="sw-rm-item">"#)
            .map(|(start, _)| {
                let rest = &html[start..];
                let end =
                    rest.find("</article>").expect("unterminated sw-rm-item") + "</article>".len();
                &rest[..end]
            })
            .collect();
        // Must not pass vacuously — if `.sw-rm-item` is ever renamed, this fails
        // loudly instead of silently checking zero cards.
        assert_eq!(slices.len(), roadmap::ROADMAP_ITEMS.len());
        for slice in slices {
            assert!(!slice.contains("sw-cat-price"));
            assert!(!slice.contains("sw-cat-install"));
            assert!(!slice.contains("sw-cat-cmd"));
            assert!(!slice.contains("data-sw-clip"));
            assert!(!slice.contains("/checkout/"));
            assert!(!slice.contains("/software/"));
            assert!(!slice.contains("SoftwareApplication"));
            assert!(!slice.contains('$'));
        }
    }

    /// Guards the concrete hazard the merge introduces: `os-console` already
    /// exists both as a real (commented-out, pending its leak investigation)
    /// `products.yaml` entry and as a live `ROADMAP_ITEMS` entry. If it's ever
    /// re-added to `products.yaml` without pruning the roadmap entry, it would
    /// silently render twice — once purchasable, once "not yet available" — in
    /// the same Delivery section.
    #[test]
    fn roadmap_ids_never_collide_with_catalog_ids() {
        let path = std::path::PathBuf::from(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/catalog/products.yaml"
        ));
        let catalog = crate::load_catalog(&path).expect("real products.yaml must parse");
        for r in roadmap::ROADMAP_ITEMS {
            assert!(
                !catalog.installers.iter().any(|i| i.id == r.id),
                "roadmap item '{}' also exists as a real products.yaml entry — it \
                 would render twice on the merged page",
                r.id
            );
        }
    }

    #[test]
    fn every_real_product_renders_in_exactly_one_tier_section() {
        let path = std::path::PathBuf::from(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/catalog/products.yaml"
        ));
        let catalog = crate::load_catalog(&path).expect("real products.yaml must parse");
        let html = catalog_markup(&catalog, BASE, Lang::En).into_string();
        for i in &catalog.installers {
            let marker = format!("sw-cat-card__id\">{}<", i.id);
            assert_eq!(
                html.matches(&marker).count(),
                1,
                "product '{}' must render in exactly one tier section",
                i.id
            );
            // And it must be inside its own declared tier's section, not a
            // different one.
            let section_marker = format!(r#"id="{}""#, i.tier.slug());
            let section_start = html.find(&section_marker).unwrap();
            let next_section_start = TIER_ORDER
                .iter()
                .filter(|t| **t != i.tier)
                .filter_map(|t| html.find(&format!(r#"id="{}""#, t.slug())))
                .filter(|pos| *pos > section_start)
                .min()
                .unwrap_or(html.len());
            let product_pos = html.find(&marker).unwrap();
            assert!(
                product_pos > section_start && product_pos < next_section_start,
                "product '{}' rendered outside its declared tier section",
                i.id
            );
        }
    }

    #[test]
    fn tier_sections_render_in_delivery_platform_infrastructure_order() {
        // Locks in the deliberate, explicit inversion of project-totebox/README.md's
        // own bottom-up engineering order — a future "fix" should not silently
        // revert this back to Infrastructure-first.
        let html = catalog_markup(&fixture(), BASE, Lang::En).into_string();
        let delivery = html.find(r#"id="delivery""#).unwrap();
        let platform = html.find(r#"id="platform""#).unwrap();
        let infrastructure = html.find(r#"id="infrastructure""#).unwrap();
        assert!(delivery < platform);
        assert!(platform < infrastructure);
    }

    #[test]
    fn archband_and_stat_strip_counts_never_exceed_real_downloadable_inventory() {
        let html = catalog_markup(&fixture(), BASE, Lang::En).into_string();
        // The "available to download" stat is real installer count, never inflated
        // by roadmap items.
        let stat_idx = html.find("sw-cat-stat__num\">").unwrap();
        let stat_val = &html[stat_idx + "sw-cat-stat__num\">".len()..];
        let stat_val = &stat_val[..stat_val.find('<').unwrap()];
        assert_eq!(
            stat_val.parse::<usize>().unwrap(),
            fixture().installers.len()
        );
    }

    /// The complexity tripwire from Phase 1b's holistic redesign — badge diet (6
    /// pills down to 2) and the fact-row cap (≤3 authored + 1 derived), enforced by
    /// test, not just design intent.
    #[test]
    fn card_emits_at_most_two_badges_and_at_most_four_fact_rows() {
        let html = catalog_markup(&fixture_with_appliance(), BASE, Lang::En).into_string();
        for id in ["test-mediakit", "test-console", "test-totebox"] {
            let marker = format!("sw-cat-card__id\">{id}<");
            let start = html.find(&marker).unwrap();
            let rest = &html[start..];
            let end = rest.find("</article>").unwrap();
            let slice = &rest[..end];
            let badge_count =
                slice.matches("sw-cat-chip").count() + slice.matches("sw-cat-badge--ver").count();
            let fact_count = slice.matches("class=\"sw-cat-fact\"").count();
            assert!(
                badge_count <= 2,
                "'{id}' emits {badge_count} badges, expected <= 2"
            );
            assert!(
                fact_count <= 4,
                "'{id}' emits {fact_count} fact rows, expected <= 4"
            );
        }
    }
}
