//! The crawled, structured representation of one wiki article: frontmatter plus every
//! structural element `markdown` extracts from the body. Deliberately holds no
//! editorial-rule-checking logic (BRIEF-tool-wiki plan Part 1) — a `Document` is a fact
//! about what an article contains, not a verdict on whether it's correct.

use std::path::PathBuf;

use crate::frontmatter::{Frontmatter, FrontmatterError};
use crate::markdown::{self, AutoGeneratedBlock, CodeBlock, Heading, MarkdownLink, Table, Wikilink};

#[derive(Debug, Clone)]
pub struct Document {
    /// Path relative to the wiki content root this document was crawled from.
    pub path: PathBuf,
    pub frontmatter: Frontmatter,
    pub body: String,
    pub headings: Vec<Heading>,
    pub wikilinks: Vec<Wikilink>,
    pub markdown_links: Vec<MarkdownLink>,
    pub code_blocks: Vec<CodeBlock>,
    pub tables: Vec<Table>,
    pub auto_generated_blocks: Vec<AutoGeneratedBlock>,
}

#[derive(Debug)]
pub enum DocumentError {
    Frontmatter(FrontmatterError),
}

impl std::fmt::Display for DocumentError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            DocumentError::Frontmatter(e) => write!(f, "{e}"),
        }
    }
}

impl std::error::Error for DocumentError {}

impl Document {
    /// Parse one article's raw file content into a `Document`. `path` is stored as-given
    /// (callers pass a path relative to the content root so `Document`s stay portable
    /// across machines and archives).
    pub fn parse(path: PathBuf, content: &str) -> Result<Document, DocumentError> {
        let (frontmatter, body) =
            Frontmatter::parse(content).map_err(DocumentError::Frontmatter)?;
        let body = body.to_string();
        let headings = markdown::headings(&body);
        let wikilinks = markdown::wikilinks(&body);
        let markdown_links = markdown::markdown_links(&body);
        let code_blocks = markdown::code_blocks(&body);
        let tables = markdown::tables(&body);
        let auto_generated_blocks = markdown::auto_generated_blocks(&body);
        Ok(Document {
            path,
            frontmatter,
            body,
            headings,
            wikilinks,
            markdown_links,
            code_blocks,
            tables,
            auto_generated_blocks,
        })
    }

    /// Word count of the body, excluding fenced code block content — matches
    /// `editorial-metrics.py`'s existing convention (code isn't prose), so a future Rust
    /// re-implementation of that script's word-density check can build on this directly.
    pub fn word_count_excluding_code(&self) -> usize {
        let mut body_without_code = self.body.clone();
        // Remove each block's full span (opening fence through closing fence, inclusive) —
        // not just the inner content — so the ` ``` ` delimiters themselves don't get
        // counted as words. Reverse order so earlier offsets stay valid as later ones are
        // removed.
        let mut blocks = self.code_blocks.clone();
        blocks.sort_by_key(|b| std::cmp::Reverse(b.offset));
        for block in blocks {
            if block.end <= body_without_code.len() {
                body_without_code.replace_range(block.offset..block.end, "");
            }
        }
        body_without_code.split_whitespace().count()
    }

    pub fn is_index_page(&self) -> bool {
        self.frontmatter.content_type() == Some("topic")
            && self
                .path
                .file_stem()
                .and_then(|s| s.to_str())
                .map(|s| s == "_index" || s.starts_with("_index."))
                .unwrap_or(false)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> &'static str {
        "---\nschema: foundry-doc-v1\ntitle: \"Demand and Demographics\"\nslug: urban\ncategory: urban\ncontent_type: topic\nstatus: active\n---\n\nDemand and Demographics covers the city-scale forces behind demand.\n\n## Commuter Belts and the Urban Fringe\n\n[[commuter|Commuter (PKS)]] and [[urban-fringe|Urban Fringe (VWH)]] are two archetypes.\n\n<!-- AUTO-GENERATED MEMBERSHIP: DO NOT EDIT BELOW — regenerate from index_group: commuter-belts-and-the-urban-fringe -->\n- [[commuter]] — desc one.\n- [[urban-fringe]] — desc two.\n<!-- END AUTO-GENERATED -->\n\n## See also\n\n- [[site-selection-index|Site Selection]]\n"
    }

    #[test]
    fn parses_a_realistic_index_article_end_to_end() {
        let doc = Document::parse(PathBuf::from("urban/_index.md"), sample()).unwrap();
        assert_eq!(doc.frontmatter.title(), Some("Demand and Demographics"));
        assert_eq!(doc.headings.len(), 2);
        // wikilinks() scans the raw body, so the AUTO-GENERATED block's own [[commuter]]/
        // [[urban-fringe]] item links count alongside the identical links used in prose —
        // 2 in prose + 2 in the AUTO block + 1 in "See also" = 5. This is correct: a caller
        // wanting only prose links should intersect against `auto_generated_blocks` ranges.
        assert_eq!(doc.wikilinks.len(), 5);
        assert_eq!(doc.auto_generated_blocks.len(), 1);
        assert_eq!(doc.auto_generated_blocks[0].items.len(), 2);
    }

    #[test]
    fn word_count_excludes_fenced_code() {
        let content = "---\ntitle: \"X\"\n---\n\nReal prose here five words.\n\n```bash\nthis code should not count as prose words at all\n```\n";
        let doc = Document::parse(PathBuf::from("x.md"), content).unwrap();
        // "Real prose here five words." = 5 words
        assert_eq!(doc.word_count_excluding_code(), 5);
    }
}
