//! Structural element extraction from a wiki article body: headings, wikilinks, tables,
//! fenced code blocks, and the AUTO-GENERATED MEMBERSHIP blocks `_index.md` pages use to
//! render category-group listings (BRIEF-tool-wiki plan Part 4 depends on parsing these
//! reliably — the regenerator function reads what this module extracts).

/// One ATX heading (`#` through `######`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Heading {
    pub level: u8,
    pub text: String,
    /// Byte offset of the heading line's start within the body, for callers that need to
    /// report a location (e.g. "heading at byte 412").
    pub offset: usize,
}

/// A `[[slug]]` or `[[slug|display text]]` wikilink.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Wikilink {
    pub target: String,
    /// `None` for a bare `[[slug]]` link — the engine renders the slug itself as the
    /// display text in that case.
    pub display: Option<String>,
    pub offset: usize,
}

/// A standard `[text](url)` markdown link — distinct from a `Wikilink`, since these point
/// at real URLs (`/category/<id>`, external sites) rather than an internal slug.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MarkdownLink {
    pub text: String,
    pub url: String,
    pub offset: usize,
}

/// A fenced code block (` ``` `-delimited), with its optional language tag.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CodeBlock {
    pub language: Option<String>,
    pub content: String,
    /// Byte offset of the opening fence line's start.
    pub offset: usize,
    /// Byte offset just past the closing fence line (inclusive of its trailing newline) —
    /// callers that need to remove the whole block, fences included, use `offset..end`
    /// rather than reconstructing it from `content.len()` (which covers only the inner
    /// lines, not the ` ``` ` delimiters themselves).
    pub end: usize,
}

/// A markdown pipe table's row/column shape — not the cell content, which the token
/// engine's future column-count check (`components-structural.yaml`'s "max 6 columns"
/// house rule) doesn't need.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Table {
    pub columns: usize,
    pub rows: usize,
    pub offset: usize,
}

/// One `<!-- AUTO-GENERATED MEMBERSHIP: DO NOT EDIT BELOW — regenerate from index_group:
/// <name> -->` ... `<!-- END AUTO-GENERATED -->` block, as used by every `_index.md` page's
/// category-group listings.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AutoGeneratedBlock {
    pub index_group: String,
    /// The `- [[slug]] — description` lines between the markers, verbatim.
    pub items: Vec<String>,
    pub offset: usize,
    /// Byte offset just past the closing `<!-- END AUTO-GENERATED -->` marker. Callers that
    /// need to know what prose sits *outside* every block (the curation layer) use
    /// `offset..end` to subtract the blocks from a section's span, the same way
    /// `CodeBlock::end` lets `word_count_excluding_code` subtract fenced code.
    pub end: usize,
}

pub fn headings(body: &str) -> Vec<Heading> {
    let mut out = Vec::new();
    let mut offset = 0usize;
    for line in body.split_inclusive('\n') {
        let trimmed = line.trim_end_matches(['\n', '\r']);
        let stripped = trimmed.trim_start();
        if let Some(hashes) = leading_hashes(stripped) {
            let level = hashes as u8;
            let text = stripped[hashes..].trim().to_string();
            if !text.is_empty() {
                out.push(Heading { level, text, offset });
            }
        }
        offset += line.len();
    }
    out
}

fn leading_hashes(s: &str) -> Option<usize> {
    let count = s.chars().take_while(|&c| c == '#').count();
    if count == 0 || count > 6 {
        return None;
    }
    // Must be followed by a space (or be the whole line) to count as a real ATX heading,
    // not e.g. a stray "###" inside prose.
    match s.as_bytes().get(count) {
        Some(b' ') | None => Some(count),
        _ => None,
    }
}

pub fn wikilinks(body: &str) -> Vec<Wikilink> {
    let mut out = Vec::new();
    let bytes = body.as_bytes();
    let mut i = 0;
    while i + 1 < bytes.len() {
        if bytes[i] == b'[' && bytes[i + 1] == b'[' {
            if let Some(end) = body[i + 2..].find("]]") {
                let inner = &body[i + 2..i + 2 + end];
                let (target, display) = match inner.split_once('|') {
                    Some((t, d)) => (t.to_string(), Some(d.to_string())),
                    None => (inner.to_string(), None),
                };
                if !target.is_empty() {
                    out.push(Wikilink { target, display, offset: i });
                }
                i += 2 + end + 2;
                continue;
            }
        }
        i += 1;
    }
    out
}

pub fn markdown_links(body: &str) -> Vec<MarkdownLink> {
    let mut out = Vec::new();
    let bytes = body.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        // Skip wikilinks -- `[[...]]` would otherwise be misread as `[` + a nested `[...]`.
        if bytes[i] == b'[' && bytes.get(i + 1) == Some(&b'[') {
            i += 2;
            continue;
        }
        if bytes[i] == b'[' {
            if let Some(close) = body[i + 1..].find(']') {
                let text_end = i + 1 + close;
                if body.as_bytes().get(text_end + 1) == Some(&b'(') {
                    if let Some(paren_close) = body[text_end + 2..].find(')') {
                        let url_end = text_end + 2 + paren_close;
                        out.push(MarkdownLink {
                            text: body[i + 1..text_end].to_string(),
                            url: body[text_end + 2..url_end].to_string(),
                            offset: i,
                        });
                        i = url_end + 1;
                        continue;
                    }
                }
            }
        }
        i += 1;
    }
    out
}

pub fn code_blocks(body: &str) -> Vec<CodeBlock> {
    let mut out = Vec::new();
    let mut offset = 0usize;
    let mut lines = body.split_inclusive('\n').peekable();
    while let Some(line) = lines.next() {
        let trimmed = line.trim_end_matches(['\n', '\r']);
        if let Some(lang) = trimmed.strip_prefix("```") {
            let language = if lang.trim().is_empty() {
                None
            } else {
                Some(lang.trim().to_string())
            };
            let block_offset = offset;
            offset += line.len();
            let mut content = String::new();
            for inner in lines.by_ref() {
                let inner_trimmed = inner.trim_end_matches(['\n', '\r']);
                offset += inner.len();
                if inner_trimmed.trim_start() == "```" {
                    break;
                }
                content.push_str(inner);
            }
            out.push(CodeBlock { language, content, offset: block_offset, end: offset });
            continue;
        }
        offset += line.len();
    }
    out
}

pub fn tables(body: &str) -> Vec<Table> {
    let mut out = Vec::new();
    let lines: Vec<&str> = body.lines().collect();
    let mut offset = 0usize;
    let mut line_offsets = Vec::with_capacity(lines.len());
    for l in &lines {
        line_offsets.push(offset);
        offset += l.len() + 1;
    }
    let mut i = 0;
    while i + 1 < lines.len() {
        let header = lines[i].trim();
        let sep = lines[i + 1].trim();
        if is_pipe_row(header) && is_separator_row(sep) {
            let columns = header.trim_matches('|').split('|').count();
            let mut rows = 0;
            let mut j = i + 2;
            while j < lines.len() && is_pipe_row(lines[j].trim()) {
                rows += 1;
                j += 1;
            }
            out.push(Table { columns, rows, offset: line_offsets[i] });
            i = j;
            continue;
        }
        i += 1;
    }
    out
}

fn is_pipe_row(line: &str) -> bool {
    line.starts_with('|') && line.len() > 1
}

fn is_separator_row(line: &str) -> bool {
    is_pipe_row(line)
        && line
            .trim_matches('|')
            .split('|')
            .all(|cell| !cell.trim().is_empty() && cell.trim().chars().all(|c| c == '-' || c == ':'))
}

pub fn auto_generated_blocks(body: &str) -> Vec<AutoGeneratedBlock> {
    const START_MARKER: &str = "<!-- AUTO-GENERATED MEMBERSHIP: DO NOT EDIT BELOW — regenerate from index_group:";
    const END_MARKER: &str = "<!-- END AUTO-GENERATED -->";

    let mut out = Vec::new();
    let mut search_from = 0usize;
    while let Some(rel_start) = body[search_from..].find(START_MARKER) {
        let start = search_from + rel_start;
        let line_end = body[start..].find('\n').map(|i| start + i).unwrap_or(body.len());
        let header_line = &body[start..line_end];
        let index_group = header_line
            .rsplit("index_group:")
            .next()
            .unwrap_or("")
            .trim()
            .trim_end_matches("-->")
            .trim()
            .to_string();

        let Some(rel_end) = body[line_end..].find(END_MARKER) else {
            break; // malformed: a start marker with no matching end -- stop rather than misparse
        };
        let block_body = &body[line_end..line_end + rel_end];
        let items: Vec<String> = block_body
            .lines()
            .map(str::trim)
            .filter(|l| l.starts_with("- "))
            .map(str::to_string)
            .collect();

        let end = line_end + rel_end + END_MARKER.len();
        out.push(AutoGeneratedBlock { index_group, items, offset: start, end });
        search_from = end;
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extracts_headings_by_level() {
        let body = "# H1\n\nSome text\n\n## H2 One\n\ntext\n\n### H3\n";
        let hs = headings(body);
        assert_eq!(hs.len(), 3);
        assert_eq!(hs[0], Heading { level: 1, text: "H1".into(), offset: 0 });
        assert_eq!(hs[1].level, 2);
        assert_eq!(hs[1].text, "H2 One");
        assert_eq!(hs[2].level, 3);
    }

    #[test]
    fn ignores_hashes_not_followed_by_space() {
        let body = "This is #notaheading in prose.\n## Real Heading\n";
        let hs = headings(body);
        assert_eq!(hs.len(), 1);
        assert_eq!(hs[0].text, "Real Heading");
    }

    #[test]
    fn extracts_piped_and_bare_wikilinks() {
        let body = "See [[commuter|Commuter (PKS)]] and [[urban-fringe]] for more.";
        let links = wikilinks(body);
        assert_eq!(links.len(), 2);
        assert_eq!(links[0].target, "commuter");
        assert_eq!(links[0].display, Some("Commuter (PKS)".into()));
        assert_eq!(links[1].target, "urban-fringe");
        assert_eq!(links[1].display, None);
    }

    #[test]
    fn does_not_misparse_wikilinks_as_markdown_links() {
        let body = "[[commuter|Commuter (PKS)]] and [Architecture](/architecture/).";
        let wiki = wikilinks(body);
        let md = markdown_links(body);
        assert_eq!(wiki.len(), 1);
        assert_eq!(md.len(), 1);
        assert_eq!(md[0].text, "Architecture");
        assert_eq!(md[0].url, "/architecture/");
    }

    #[test]
    fn extracts_fenced_code_block_with_language() {
        let body = "Some text.\n\n```bash\ngit status\ngit push\n```\n\nMore text.\n";
        let blocks = code_blocks(body);
        assert_eq!(blocks.len(), 1);
        assert_eq!(blocks[0].language, Some("bash".into()));
        assert_eq!(blocks[0].content, "git status\ngit push\n");
    }

    #[test]
    fn extracts_pipe_table_dimensions() {
        let body = "| a | b | c |\n|---|---|---|\n| 1 | 2 | 3 |\n| 4 | 5 | 6 |\n";
        let ts = tables(body);
        assert_eq!(ts.len(), 1);
        assert_eq!(ts[0].columns, 3);
        assert_eq!(ts[0].rows, 2);
    }

    #[test]
    fn extracts_auto_generated_membership_block() {
        let body = "## Commuter Belts\n\nSome intro prose.\n\n\
<!-- AUTO-GENERATED MEMBERSHIP: DO NOT EDIT BELOW — regenerate from index_group: commuter-belts-and-the-urban-fringe -->\n\
- [[commuter]] — Commuter (PKS) clusters identify transit-adjacent sites.\n\
- [[urban-fringe]] — Urban Fringe (VWH) clusters identify large-format retail.\n\
<!-- END AUTO-GENERATED -->\n\n## See also\n";
        let blocks = auto_generated_blocks(body);
        assert_eq!(blocks.len(), 1);
        assert_eq!(blocks[0].index_group, "commuter-belts-and-the-urban-fringe");
        assert_eq!(blocks[0].items.len(), 2);
        assert!(blocks[0].items[0].starts_with("- [[commuter]]"));
        // The span must cover the whole block, closing marker included, so a caller can
        // subtract it from a section and be left with only hand-written prose.
        assert!(body[blocks[0].offset..blocks[0].end].starts_with("<!-- AUTO-GENERATED"));
        assert!(body[blocks[0].offset..blocks[0].end].ends_with("<!-- END AUTO-GENERATED -->"));
        assert!(!body[blocks[0].end..].contains("END AUTO-GENERATED"));
    }

    #[test]
    fn handles_multiple_auto_generated_blocks_in_one_body() {
        let body = "\
<!-- AUTO-GENERATED MEMBERSHIP: DO NOT EDIT BELOW — regenerate from index_group: group-one -->\n\
- [[a]] — desc\n\
<!-- END AUTO-GENERATED -->\n\n\
<!-- AUTO-GENERATED MEMBERSHIP: DO NOT EDIT BELOW — regenerate from index_group: group-two -->\n\
- [[b]] — desc\n\
- [[c]] — desc\n\
<!-- END AUTO-GENERATED -->\n";
        let blocks = auto_generated_blocks(body);
        assert_eq!(blocks.len(), 2);
        assert_eq!(blocks[0].index_group, "group-one");
        assert_eq!(blocks[0].items.len(), 1);
        assert_eq!(blocks[1].index_group, "group-two");
        assert_eq!(blocks[1].items.len(), 2);
    }

    #[test]
    fn malformed_start_marker_with_no_end_does_not_panic() {
        let body = "<!-- AUTO-GENERATED MEMBERSHIP: DO NOT EDIT BELOW — regenerate from index_group: orphan -->\n- [[a]] — desc\n";
        let blocks = auto_generated_blocks(body);
        assert!(blocks.is_empty());
    }
}
