[Interface]
PrivateKey = 
Address = 10.8.0.2/32
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = <REDACTED-VPN-SERVER-PUBLIC-KEY>
Endpoint = <REDACTED-VPN-ENDPOINT-IP>:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
