// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Woodfine Capital Projects Inc.

//! Phase 4 (DTCG token wiring): generates `static/tokens.css` from
//! `tokens/design-tokens.json` (the DTCG-format source of truth for the
//! theme-neutral base tokens) plus `tokens/theme-overrides.css` (the
//! hand-maintained per-tenant/dark-mode selector overrides — DTCG has no
//! stable multi-mode standard to drive those from yet).
//!
//! Runs on every `cargo build`; `rust_embed`'s `#[folder = "static/"]` reads
//! the directory at compile time, after build.rs has run, so the freshly
//! generated file is what gets embedded.

use std::collections::BTreeMap;
use std::path::Path;

use serde_json::Value;

fn main() {
    println!("cargo:rerun-if-changed=tokens/design-tokens.json");
    println!("cargo:rerun-if-changed=tokens/theme-overrides.css");

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set");
    let tokens_path = Path::new(&manifest_dir).join("tokens/design-tokens.json");
    let overrides_path = Path::new(&manifest_dir).join("tokens/theme-overrides.css");
    let out_path = Path::new(&manifest_dir).join("static/tokens.css");

    let json_text = std::fs::read_to_string(&tokens_path)
        .unwrap_or_else(|e| panic!("reading {}: {e}", tokens_path.display()));
    let doc: Value = serde_json::from_str(&json_text)
        .unwrap_or_else(|e| panic!("parsing {}: {e}", tokens_path.display()));
    let overrides = std::fs::read_to_string(&overrides_path)
        .unwrap_or_else(|e| panic!("reading {}: {e}", overrides_path.display()));

    let base_block = generate_base_block(&doc);

    let generated = format!(
        "/*\n * SPDX-License-Identifier: Apache-2.0\n * SPDX-FileCopyrightText: 2026 Woodfine Capital Projects Inc.\n *\n * GENERATED FILE — do not edit directly. The base :root block below is\n * generated by build.rs from tokens/design-tokens.json (DTCG format);\n * everything after it is tokens/theme-overrides.css, appended verbatim.\n */\n\n:root {{\n{base_block}}}\n\n{overrides}"
    );

    std::fs::write(&out_path, generated)
        .unwrap_or_else(|e| panic!("writing {}: {e}", out_path.display()));
}

/// First pass: collect every leaf token's `$var` keyed by its DTCG alias path
/// (`"group.token"`), so `{group.token}` references can resolve to
/// `var(--k-<var>)`.
fn collect_var_index(doc: &Value) -> BTreeMap<String, String> {
    let mut index = BTreeMap::new();
    let Value::Object(groups) = doc else {
        return index;
    };
    for (group_name, group) in groups {
        if group_name.starts_with('$') {
            continue;
        }
        let Value::Object(tokens) = group else {
            continue;
        };
        for (token_name, token) in tokens {
            let Value::Object(fields) = token else {
                continue;
            };
            if let Some(Value::String(var)) = fields.get("$var") {
                index.insert(format!("{group_name}.{token_name}"), var.clone());
            }
        }
    }
    index
}

/// Resolves a single `$value` to its final CSS text. DTCG aliases
/// (`"{group.token}"`, the entire string) become `var(--k-<var>)`; a
/// `cubicBezier` array becomes `cubic-bezier(a, b, c, d)`; everything else
/// (already-valid CSS, including embedded `var(--k-...)` references) passes
/// through unchanged.
fn resolve_value(field_type: &str, value: &Value, var_index: &BTreeMap<String, String>) -> String {
    if field_type == "cubicBezier" {
        let Value::Array(nums) = value else {
            panic!("cubicBezier $value must be an array, got {value:?}");
        };
        let parts: Vec<String> = nums
            .iter()
            .map(|n| {
                n.as_f64()
                    .expect("cubicBezier element is a number")
                    .to_string()
            })
            .collect();
        return format!("cubic-bezier({})", parts.join(", "));
    }
    match value {
        Value::String(s) => {
            if let Some(inner) = s.strip_prefix('{').and_then(|s| s.strip_suffix('}')) {
                let var = var_index
                    .get(inner)
                    .unwrap_or_else(|| panic!("unresolved token alias: {{{inner}}}"));
                format!("var(--k-{var})")
            } else {
                s.clone()
            }
        }
        Value::Number(n) => n.to_string(),
        other => panic!("unsupported $value shape: {other:?}"),
    }
}

fn generate_base_block(doc: &Value) -> String {
    let var_index = collect_var_index(doc);
    let mut out = String::new();
    let Value::Object(groups) = doc else {
        panic!("design-tokens.json root must be an object");
    };
    for (group_name, group) in groups {
        if group_name.starts_with('$') {
            continue;
        }
        let Value::Object(tokens) = group else {
            continue;
        };
        for (_token_name, token) in tokens {
            let Value::Object(fields) = token else {
                continue;
            };
            let var = fields
                .get("$var")
                .and_then(Value::as_str)
                .unwrap_or_else(|| panic!("token in group {group_name} missing $var"));
            let field_type = fields
                .get("$type")
                .and_then(Value::as_str)
                .unwrap_or_else(|| panic!("--k-{var} missing $type"));
            let raw_value = fields
                .get("$value")
                .unwrap_or_else(|| panic!("--k-{var} missing $value"));
            let resolved = resolve_value(field_type, raw_value, &var_index);
            match fields.get("$description").and_then(Value::as_str) {
                Some(desc) if !desc.is_empty() => {
                    out.push_str(&format!("  --k-{var}: {resolved}; /* {desc} */\n"));
                }
                _ => out.push_str(&format!("  --k-{var}: {resolved};\n")),
            }
        }
    }
    out
}
