// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Apprenticeship Substrate types — brief / attempt / verdict.
//!
//! Per Doctrine claim #32 and
//! `~/Foundry/conventions/apprenticeship-substrate.md`. The Doorman flips
//! polarity: service-slm becomes first responder on code-shaped work,
//! Master / Root / Task Claude becomes senior reviewer. The disagreement
//! between them — captured as signed, append-only training tuples — is
//! the highest-quality continued-pretraining signal Foundry can produce.
//!
//! These three types are the wire shape exchanged across the three
//! apprenticeship endpoints (`POST /v1/brief`, `POST /v1/verdict`,
//! `POST /v1/shadow`). They round-trip through serde so the Doorman, the
//! `bin/apprentice.sh` helper (forthcoming AS-5), and the corpus writer
//! all read the same schema.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::tier::Tier;

/// Senior role per `apprenticeship-substrate.md` §3. Free-form
/// `root-<repo-name>` and `task-<cluster-name>` are valid; the Doorman
/// does not validate the suffix at type-level (the `senior_identity`
/// signature is what binds authority).
#[derive(Clone, Debug, Serialize, Deserialize, Eq, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum SeniorRole {
    Master,
    /// `root-<repo-name>` (suffix carried in the inner string)
    #[serde(untagged)]
    Root(String),
    /// `task-<cluster-name>`
    #[serde(untagged)]
    Task(String),
}

/// Brief scope — convention §3.
#[derive(Clone, Debug, Serialize, Deserialize, Default)]
pub struct BriefScope {
    /// Cluster name when the brief is cluster-scoped; null for
    /// workspace-scoped briefs.
    #[serde(default)]
    pub cluster: Option<String>,
    /// File paths the apprentice must consult, resolved by the Doorman
    /// against `FOUNDRY_ROOT` and inlined (post-redaction) into the
    /// apprentice prompt. Convention §3 + design-pass Q4.
    #[serde(default)]
    pub files: Vec<String>,
}

/// Senior's brief to the apprentice — convention §3.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ApprenticeshipBrief {
    /// ULID set by the senior. Used as the corpus filename (so a brief
    /// is always traceable to one row regardless of attempt count).
    pub brief_id: String,
    pub created: DateTime<Utc>,
    pub senior_role: SeniorRole,
    /// One of the four `~/Foundry/identity/allowed_signers` principals
    /// (e.g. `ps-administrator`, `jwoodfine`, `pwoodfine`,
    /// `mcorp-administrator`).
    pub senior_identity: String,
    /// Registered task-type label per
    /// `data/apprenticeship/ledger.md`. The Doorman does not enforce
    /// registration at brief time; the ledger writer enforces at
    /// verdict time.
    pub task_type: String,
    pub scope: BriefScope,
    /// Plain-text test the apprentice's diff must pass (convention §3).
    pub acceptance_test: String,
    /// Citation IDs that resolve against `~/Foundry/citations.yaml`.
    #[serde(default)]
    pub doctrine_citations: Vec<String>,
    /// `true` = corpus capture only, no production routing.
    /// Treated equivalently to a `/v1/shadow` POST when set on a
    /// `/v1/brief` request (defensive belt-and-braces).
    #[serde(default)]
    pub shadow: bool,
    /// Plain-English brief body. Convention §3: state invariants,
    /// bound the diff scope, cite doctrine clauses by ID.
    pub body: String,
}

/// Apprentice's attempt at the brief — convention §4. Returned in the
/// body of `POST /v1/brief` and captured into the corpus.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ApprenticeshipAttempt {
    pub brief_id: String,
    /// UUIDv7 hex generated by the Doorman per design-pass Q8.
    pub attempt_id: String,
    pub created: DateTime<Utc>,
    /// Apprentice model identifier — one of `olmo-3-1125-7b-q4`
    /// (Tier A) or `olmo-3-1125-32b-think-q4` (Tier B). Convention §4.
    pub model: String,
    /// Adapter IDs composed at request time per claim #22 algebra.
    /// Convention §4.
    #[serde(default)]
    pub adapter_composition: Vec<String>,
    /// 0.0..=1.0 scalar parsed from the apprentice's response. Below
    /// `APPRENTICE_ESCALATE_THRESHOLD` the Doorman empties `diff` and
    /// sets `escalate = true` (convention §4 + design-pass Q2).
    pub self_confidence: f32,
    /// `true` when the apprentice declined to attempt (low confidence
    /// or explicit escalate marker in its response).
    pub escalate: bool,
    pub inference_ms: u64,
    pub tier: Tier,
    pub cost_usd: f64,
    /// Apprentice's chain-of-thought, citing brief invariants and
    /// doctrine clauses (convention §4).
    pub reasoning: String,
    /// Unified diff against the working tree, or empty when
    /// `escalate = true`.
    pub diff: String,
}

/// Verdict outcome — convention §5.
#[derive(Clone, Copy, Debug, Serialize, Deserialize, Eq, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum VerdictOutcome {
    Accept,
    Refine,
    Reject,
    DeferTierC,
}

impl VerdictOutcome {
    pub fn as_str(&self) -> &'static str {
        match self {
            VerdictOutcome::Accept => "accept",
            VerdictOutcome::Refine => "refine",
            VerdictOutcome::Reject => "reject",
            VerdictOutcome::DeferTierC => "defer-tier-c",
        }
    }

    /// `true` when the outcome implies a corrected diff was authored
    /// the existing way; `refine` and `reject` produce DPO pairs per
    /// convention §8 + `trajectory-substrate.md` §6.
    pub fn produces_dpo_pair(&self) -> bool {
        matches!(self, VerdictOutcome::Refine | VerdictOutcome::Reject)
    }
}

/// Senior's signed verdict — convention §5. The `signature` field
/// carries the SSH signature blob (base64-encoded; see design-pass Q5)
/// over `body`. The `-n` namespace tag binds the signature to this
/// protocol so a commit-signing signature cannot be repurposed.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ApprenticeshipVerdict {
    pub brief_id: String,
    pub attempt_id: String,
    pub verdict: VerdictOutcome,
    pub created: DateTime<Utc>,
    pub senior_identity: String,
    /// Commit SHA of the corrected diff when `verdict == accept` (and
    /// the apprentice diff was applied verbatim) or when the senior
    /// produced a corrected commit themselves (refine / reject).
    /// Null when the apprentice's diff was rejected outright with no
    /// replacement.
    #[serde(default)]
    pub final_diff_sha: Option<String>,
    /// Required for `refine` / `reject`; one-sentence reason per
    /// convention §5.
    #[serde(default)]
    pub notes: Option<String>,
    /// Verbatim verdict-file content as signed (frontmatter + body
    /// prose, with `#`-comment lines stripped per the template).
    pub body: String,
    /// Base64-encoded SSH signature blob bound to `body` under
    /// namespace `apprenticeship-verdict-v1` (or
    /// `apprenticeship-verdict-batch-v1` for batch signing).
    pub signature: String,
}

/// Self-confidence threshold below which the Doorman forces
/// `escalate = true` and empties the diff. Convention §4 + design-pass
/// Q2. Tunable in one place; surface to Master once n≥10 ledger
/// evidence accrues on the first task-type.
pub const APPRENTICE_ESCALATE_THRESHOLD: f32 = 0.5;

/// Default character-budget proxy for Tier-B routing on `/v1/brief`.
/// `body.len() + acceptance_test.len()` above this threshold dispatches
/// to Tier B. Roughly 4 chars/token ≈ 2000 tokens. Design-pass Q6.
pub const DEFAULT_BRIEF_TIER_B_THRESHOLD_CHARS: usize = 8000;

/// SSH signature namespace tag for single verdicts. Bound by
/// `ssh-keygen -Y sign -n apprenticeship-verdict-v1` so a verdict
/// signature cannot be repurposed as a commit signature. Convention §5.
pub const VERDICT_NAMESPACE: &str = "apprenticeship-verdict-v1";

/// SSH signature namespace tag for session-end batch verdicts.
/// Convention §5 default.
pub const VERDICT_BATCH_NAMESPACE: &str = "apprenticeship-verdict-batch-v1";

#[cfg(test)]
mod tests {
    use super::*;

    fn ts() -> DateTime<Utc> {
        // Stable instant for round-trip equality; chrono parses RFC 3339.
        DateTime::parse_from_rfc3339("2026-04-26T15:55:00Z")
            .unwrap()
            .with_timezone(&Utc)
    }

    fn brief() -> ApprenticeshipBrief {
        ApprenticeshipBrief {
            brief_id: "01J9Q8K0ZA9R8N3WGF8V7M2H7E".into(),
            created: ts(),
            senior_role: SeniorRole::Master,
            senior_identity: "ps-administrator".into(),
            task_type: "version-bump-manifest".into(),
            scope: BriefScope {
                cluster: None,
                files: vec!["MANIFEST.md".into(), "CHANGELOG.md".into()],
            },
            acceptance_test: "MANIFEST.md source_version line bumped; CHANGELOG.md \
                              top entry added; tag created and signed."
                .into(),
            doctrine_citations: vec!["ni-51-102".into(), "olmo3-allenai".into()],
            shadow: false,
            body: "Bump workspace MINOR to v0.2.0 reflecting the apprenticeship \
                   substrate ratification."
                .into(),
        }
    }

    fn attempt() -> ApprenticeshipAttempt {
        ApprenticeshipAttempt {
            brief_id: brief().brief_id,
            attempt_id: "0192e1f8-c000-7a31-9c00-000000000001".into(),
            created: ts(),
            model: "olmo-3-1125-7b-q4".into(),
            adapter_composition: vec![
                "constitutional-doctrine".into(),
                "engineering-pointsav".into(),
                "role-task".into(),
                "cluster-project-slm".into(),
            ],
            self_confidence: 0.82,
            escalate: false,
            inference_ms: 1234,
            tier: Tier::Local,
            cost_usd: 0.0,
            reasoning: "Per ni-51-102 forward-looking marker, ...".into(),
            diff: "--- a/MANIFEST.md\n+++ b/MANIFEST.md\n@@ ...\n".into(),
        }
    }

    fn verdict() -> ApprenticeshipVerdict {
        ApprenticeshipVerdict {
            brief_id: brief().brief_id,
            attempt_id: attempt().attempt_id,
            verdict: VerdictOutcome::Accept,
            created: ts(),
            senior_identity: "ps-administrator".into(),
            final_diff_sha: Some("0123456789abcdef0123456789abcdef01234567".into()),
            notes: None,
            body: "---\nschema: foundry-apprentice-verdict-v1\n...\n---\n\nLGTM.\n".into(),
            // Not a real signature — tests round-trip the schema, not
            // crypto. AS-3 covers `ssh-keygen -Y verify`.
            signature: "AAAAC3NzaC1lZDI1NTE5DUMMYBASE64==".into(),
        }
    }

    #[test]
    fn brief_round_trips_via_json() {
        let b = brief();
        let s = serde_json::to_string(&b).unwrap();
        let b2: ApprenticeshipBrief = serde_json::from_str(&s).unwrap();
        assert_eq!(b.brief_id, b2.brief_id);
        assert_eq!(b.task_type, b2.task_type);
        assert_eq!(b.scope.files, b2.scope.files);
        assert_eq!(b.doctrine_citations, b2.doctrine_citations);
        assert_eq!(b.shadow, b2.shadow);
        assert_eq!(b.body, b2.body);
    }

    #[test]
    fn attempt_round_trips_via_json() {
        let a = attempt();
        let s = serde_json::to_string(&a).unwrap();
        let a2: ApprenticeshipAttempt = serde_json::from_str(&s).unwrap();
        assert_eq!(a.brief_id, a2.brief_id);
        assert_eq!(a.attempt_id, a2.attempt_id);
        assert_eq!(a.tier, a2.tier);
        assert!((a.self_confidence - a2.self_confidence).abs() < 1e-6);
        assert_eq!(a.escalate, a2.escalate);
        assert_eq!(a.adapter_composition, a2.adapter_composition);
        assert_eq!(a.diff, a2.diff);
    }

    #[test]
    fn verdict_round_trips_via_json() {
        let v = verdict();
        let s = serde_json::to_string(&v).unwrap();
        let v2: ApprenticeshipVerdict = serde_json::from_str(&s).unwrap();
        assert_eq!(v.brief_id, v2.brief_id);
        assert_eq!(v.attempt_id, v2.attempt_id);
        assert_eq!(v.verdict, v2.verdict);
        assert_eq!(v.senior_identity, v2.senior_identity);
        assert_eq!(v.final_diff_sha, v2.final_diff_sha);
        assert_eq!(v.body, v2.body);
        assert_eq!(v.signature, v2.signature);
    }

    #[test]
    fn verdict_outcome_round_trips_kebab_case() {
        for v in [
            VerdictOutcome::Accept,
            VerdictOutcome::Refine,
            VerdictOutcome::Reject,
            VerdictOutcome::DeferTierC,
        ] {
            let s = serde_json::to_string(&v).unwrap();
            let v2: VerdictOutcome = serde_json::from_str(&s).unwrap();
            assert_eq!(v, v2);
        }
        // Wire form check — defer-tier-c uses the kebab-case spelling
        // from the brief / convention §5.
        assert_eq!(
            serde_json::to_string(&VerdictOutcome::DeferTierC).unwrap(),
            "\"defer-tier-c\""
        );
    }

    #[test]
    fn verdict_outcome_dpo_pair_classification() {
        assert!(!VerdictOutcome::Accept.produces_dpo_pair());
        assert!(VerdictOutcome::Refine.produces_dpo_pair());
        assert!(VerdictOutcome::Reject.produces_dpo_pair());
        assert!(!VerdictOutcome::DeferTierC.produces_dpo_pair());
    }

    #[test]
    fn senior_role_serialises_master_canonically() {
        let s = serde_json::to_string(&SeniorRole::Master).unwrap();
        assert_eq!(s, "\"master\"");
        let r: SeniorRole = serde_json::from_str(&s).unwrap();
        assert_eq!(r, SeniorRole::Master);
    }
}
